/*
 * gpi-irqs.h- Sigmastar
 *
 * Copyright (c) [2019~2020] SigmaStar Technology.
 *
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details.
 *
 */
/*------------------------------------------------------------------------------

------------------------------------------------------------------------------*/

#ifndef _GPI_IRQS_H_
#define _GPI_IRQS_H_

#define GPI_FIQ_START                0
#define INT_GPI_FIQ_PAD_I2C1_SDA     (GPI_FIQ_START + 0)
#define INT_GPI_FIQ_PAD_SR_RST0      (GPI_FIQ_START + 1)
#define INT_GPI_FIQ_PAD_SR_MCLK0     (GPI_FIQ_START + 2)
#define INT_GPI_FIQ_PAD_I2C1_SCL     (GPI_FIQ_START + 3)
#define INT_GPI_FIQ_PAD_SR_RST1      (GPI_FIQ_START + 4)
#define INT_GPI_FIQ_PAD_SR_MCLK1     (GPI_FIQ_START + 5)
#define INT_GPI_FIQ_PAD_I2C2_SCL     (GPI_FIQ_START + 6)
#define INT_GPI_FIQ_PAD_I2C2_SDA     (GPI_FIQ_START + 7)
#define INT_GPI_FIQ_PAD_GPIO0        (GPI_FIQ_START + 8)
#define INT_GPI_FIQ_PAD_GPIO1        (GPI_FIQ_START + 9)
#define INT_GPI_FIQ_PAD_GPIO2        (GPI_FIQ_START + 10)
#define INT_GPI_FIQ_PAD_GPIO3        (GPI_FIQ_START + 11)
#define INT_GPI_FIQ_PAD_GPIO4        (GPI_FIQ_START + 12)
#define INT_GPI_FIQ_PAD_GPIO5        (GPI_FIQ_START + 13)
#define INT_GPI_FIQ_PAD_GPIO6        (GPI_FIQ_START + 14)
#define INT_GPI_FIQ_PAD_GPIO7        (GPI_FIQ_START + 15)
#define INT_GPI_FIQ_PAD_GPIO8        (GPI_FIQ_START + 16)
#define INT_GPI_FIQ_PAD_GPIO9        (GPI_FIQ_START + 17)
#define INT_GPI_FIQ_PAD_GPIO10       (GPI_FIQ_START + 18)
#define INT_GPI_FIQ_PAD_GPIO11       (GPI_FIQ_START + 19)
#define INT_GPI_FIQ_PAD_SD0_CDZ      (GPI_FIQ_START + 20)
#define INT_GPI_FIQ_PAD_SD0_D1       (GPI_FIQ_START + 21)
#define INT_GPI_FIQ_PAD_SD0_D0       (GPI_FIQ_START + 22)
#define INT_GPI_FIQ_PAD_SD0_CLK      (GPI_FIQ_START + 23)
#define INT_GPI_FIQ_PAD_SD0_CMD      (GPI_FIQ_START + 24)
#define INT_GPI_FIQ_PAD_SD0_D3       (GPI_FIQ_START + 25)
#define INT_GPI_FIQ_PAD_SD0_D2       (GPI_FIQ_START + 26)
#define INT_GPI_FIQ_PAD_FUART_RTS    (GPI_FIQ_START + 27)
#define INT_GPI_FIQ_PAD_FUART_CTS    (GPI_FIQ_START + 28)
#define INT_GPI_FIQ_PAD_FUART_RX     (GPI_FIQ_START + 29)
#define INT_GPI_FIQ_PAD_FUART_TX     (GPI_FIQ_START + 30)
#define INT_GPI_FIQ_PAD_MSPI_CZ      (GPI_FIQ_START + 31)
#define INT_GPI_FIQ_PAD_MSPI_DO      (GPI_FIQ_START + 32)
#define INT_GPI_FIQ_PAD_MSPI_DI      (GPI_FIQ_START + 33)
#define INT_GPI_FIQ_PAD_MSPI_CK      (GPI_FIQ_START + 34)
#define INT_GPI_FIQ_PAD_SPI0_DO      (GPI_FIQ_START + 35)
#define INT_GPI_FIQ_PAD_SPI0_DI      (GPI_FIQ_START + 36)
#define INT_GPI_FIQ_PAD_SPI0_HLD     (GPI_FIQ_START + 37)
#define INT_GPI_FIQ_PAD_SPI0_WPZ     (GPI_FIQ_START + 38)
#define INT_GPI_FIQ_PAD_SPI0_CZ      (GPI_FIQ_START + 39)
#define INT_GPI_FIQ_PAD_SPI0_CK      (GPI_FIQ_START + 40)
#define INT_GPI_FIQ_PAD_I2C0_SDA     (GPI_FIQ_START + 41)
#define INT_GPI_FIQ_PAD_I2C0_SCL     (GPI_FIQ_START + 42)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH5 (GPI_FIQ_START + 95)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH5 (GPI_FIQ_START + 96)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH4 (GPI_FIQ_START + 97)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH4 (GPI_FIQ_START + 98)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH3 (GPI_FIQ_START + 99)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH3 (GPI_FIQ_START + 100)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH2 (GPI_FIQ_START + 101)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH2 (GPI_FIQ_START + 102)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH1 (GPI_FIQ_START + 103)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH1 (GPI_FIQ_START + 104)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH0 (GPI_FIQ_START + 105)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH0 (GPI_FIQ_START + 106)
#define GPI_FIQ_END                  (GPI_FIQ_START + 107)

#define GPI_GPIC_START    (GPI_FIQ_START + 130)
#define INT_GPI_FIQ_GPIC0 (GPI_GPIC_START + 0)
#define INT_GPI_FIQ_GPIC1 (GPI_GPIC_START + 1)
#define GPI_GPIC_END      (GPI_GPIC_START + 2)

#define GPI_FIQ_NUM  (GPI_FIQ_END - GPI_FIQ_START)
#define GPI_GPIC_NUM (GPI_GPIC_END - GPI_GPIC_START)

#define PM_GPI_FIQ_START                   0
#define INT_PM_GPI_FIQ_PAD_PM_GPIO12       (PM_GPI_FIQ_START + 0)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO11       (PM_GPI_FIQ_START + 1)
#define INT_PM_GPI_FIQ_PAD_PM_UART_TX      (PM_GPI_FIQ_START + 2)
#define INT_PM_GPI_FIQ_PAD_PM_UART_RX      (PM_GPI_FIQ_START + 3)
#define INT_PM_GPI_FIQ_PAD_PM_PSPI0_INT    (PM_GPI_FIQ_START + 4)
#define INT_PM_GPI_FIQ_PAD_PM_PSPI0_DI     (PM_GPI_FIQ_START + 5)
#define INT_PM_GPI_FIQ_PAD_PM_PSPI0_DO     (PM_GPI_FIQ_START + 6)
#define INT_PM_GPI_FIQ_PAD_PM_PSPI0_CK     (PM_GPI_FIQ_START + 7)
#define INT_PM_GPI_FIQ_PAD_PM_PSPI0_CZ     (PM_GPI_FIQ_START + 8)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO10       (PM_GPI_FIQ_START + 9)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO9        (PM_GPI_FIQ_START + 10)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO8        (PM_GPI_FIQ_START + 11)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO7        (PM_GPI_FIQ_START + 12)
#define INT_PM_GPI_FIQ_PAD_PM_PWM3         (PM_GPI_FIQ_START + 13)
#define INT_PM_GPI_FIQ_PAD_PM_PWM2         (PM_GPI_FIQ_START + 14)
#define INT_PM_GPI_FIQ_PAD_PM_PWM1         (PM_GPI_FIQ_START + 15)
#define INT_PM_GPI_FIQ_PAD_PM_PWM0         (PM_GPI_FIQ_START + 16)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO6        (PM_GPI_FIQ_START + 17)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO5        (PM_GPI_FIQ_START + 18)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO4        (PM_GPI_FIQ_START + 19)
#define INT_PM_GPI_FIQ_PAD_PM_UART2_TX     (PM_GPI_FIQ_START + 20)
#define INT_PM_GPI_FIQ_PAD_PM_UART2_RX     (PM_GPI_FIQ_START + 21)
#define INT_PM_GPI_FIQ_PAD_PM_I2C_CLK      (PM_GPI_FIQ_START + 22)
#define INT_PM_GPI_FIQ_PAD_PM_I2C_SDA      (PM_GPI_FIQ_START + 23)
#define INT_PM_GPI_FIQ_PAD_PM_SDIO_INT     (PM_GPI_FIQ_START + 24)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO3        (PM_GPI_FIQ_START + 25)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO2        (PM_GPI_FIQ_START + 26)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO1        (PM_GPI_FIQ_START + 27)
#define INT_PM_GPI_FIQ_PAD_PM_GPIO0        (PM_GPI_FIQ_START + 28)
#define INT_PM_GPI_FIQ_PAD_PM_SDIO_D1      (PM_GPI_FIQ_START + 29)
#define INT_PM_GPI_FIQ_PAD_PM_SDIO_D0      (PM_GPI_FIQ_START + 30)
#define INT_PM_GPI_FIQ_PAD_PM_SDIO_CLK     (PM_GPI_FIQ_START + 31)
#define INT_PM_GPI_FIQ_PAD_PM_SDIO_CMD     (PM_GPI_FIQ_START + 32)
#define INT_PM_GPI_FIQ_PAD_PM_SDIO_D3      (PM_GPI_FIQ_START + 33)
#define INT_PM_GPI_FIQ_PAD_PM_SDIO_D2      (PM_GPI_FIQ_START + 34)
#define INT_PM_GPI_FIQ_PAD_PM_FUART_RTS    (PM_GPI_FIQ_START + 35)
#define INT_PM_GPI_FIQ_PAD_PM_FUART_CTS    (PM_GPI_FIQ_START + 36)
#define INT_PM_GPI_FIQ_PAD_PM_FUART_RX     (PM_GPI_FIQ_START + 37)
#define INT_PM_GPI_FIQ_PAD_PM_FUART_TX     (PM_GPI_FIQ_START + 38)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO0  (PM_GPI_FIQ_START + 39)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO1  (PM_GPI_FIQ_START + 40)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO2  (PM_GPI_FIQ_START + 41)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO3  (PM_GPI_FIQ_START + 42)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO4  (PM_GPI_FIQ_START + 43)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO5  (PM_GPI_FIQ_START + 44)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO6  (PM_GPI_FIQ_START + 45)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO7  (PM_GPI_FIQ_START + 46)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO8  (PM_GPI_FIQ_START + 47)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO9  (PM_GPI_FIQ_START + 48)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO10 (PM_GPI_FIQ_START + 49)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO11 (PM_GPI_FIQ_START + 50)
#define INT_PM_GPI_FIQ_PAD_PM_HSRAM_GPIO12 (PM_GPI_FIQ_START + 51)
#define INT_PM_GPI_FIQ_PAD_RTC_IO0         (PM_GPI_FIQ_START + 58)
#define INT_PM_GPI_FIQ_PAD_RTC_IO1         (PM_GPI_FIQ_START + 59)
#define INT_PM_GPI_FIQ_PAD_RTC_IO2         (PM_GPI_FIQ_START + 60)
#define INT_PM_GPI_FIQ_PAD_RTC_IO3         (PM_GPI_FIQ_START + 61)
#define PM_GPI_FIQ_END                     (PM_GPI_FIQ_START + 62)

#define PM_GPI_FIQ_NUM (PM_GPI_FIQ_END - PM_GPI_FIQ_START)

#endif /* _GPI_IRQS_H_ */
