MODULES_1st:=    \
	mi_common.ko \
	mi_sys.ko    \
	mi_aio.ko   \
	mi_ao.ko   \
	mi_rgn.ko \
	mi_vif.ko    \
	mi_sensor.ko   \
	mi_isp.ko   \
	mi_ipu.ko   \
	mi_ai.ko   \
	mi_ldc.ko   \
	kdrv_sdmmc.ko  \
	mmc_core.ko    \
	mmc_block.ko   \
	mi_scl.ko   \
	mi_venc.ko	\
	mi_vdf.ko	\
MODULES_2nd:=   \
	mi_iqserver.ko    \
	mi_panel.ko    \
	mi_disp.ko    \
	usb-common.ko   \
	usbcore.ko  \
	scsi_mod.ko \
	cifs.ko     \
	grace.ko    \
	sunrpc.ko   \
	lockd.ko    \
	nfs.ko      \
	nfsv2.ko    \
	fat.ko       \
	msdos.ko     \
	vfat.ko      \
	ntfs.ko      \
	sd_mod.ko    \
	jffs2.ko     \
	ubi.ko       \
	ubifs.ko     \
	mii.ko       \
	kdrv_emac.ko \
	mi_fb.ko    \
LIBS_1st:= \
	libmi_common.so \
	libmi_sys.so    \
	libmi_rgn.so    \
	libmi_ao.so \
	libmi_vif.so \
	libmi_sensor.so \
	libmi_ldc.so    \
	libmi_isp.so    \
	libmi_ipu.so   \
	libmi_shadow.so    \
	libmi_ai.so \
	libfbc_decode.so \
	libmi_venc.so   \
	libispalgo.so   \
	libcus3a.so     \
	libcam_os_wrapper.so    \
	libcam_fs_wrapper.so    \

LIBS_2nd:= \
	libmi_vpe.so    \
	libmi_vdisp.so   \
	libmi_iqserver.so \
	libmi_vdf.so \
	libmi_divp.so    \
	libmi_ive.so \
	libOD_LINUX.so \
	libMD_LINUX.so \
	libVG_LINUX.so \
	libAPC_LINUX.so \
	libAEC_LINUX.so \
	libSRC_LINUX.so \
	libg711.so \
	libg726.so \
	libmi_sed.so \
