/*
 * audio_bank1_sw_reg_define.h - Sigmastar
 *
 * Copyright (c) [2019~2022] SigmaStar Technology.
 *
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details.
 *
 */

#ifndef __JM_AUDIO_BANK1_SW_REG_DEFINE_H__
#define __JM_AUDIO_BANK1_SW_REG_DEFINE_H__

#define AUDIO_BANK1_REG_DMA_1_DIFF_ADDR                    0x00
#define AUDIO_BANK1_REG_DMA_1_DIFF_REG_DMA_1_RW_DIFF_MASK  0xffff
#define AUDIO_BANK1_REG_DMA_1_DIFF_REG_DMA_1_RW_DIFF_SHIFT 0

#define AUDIO_BANK1_REG_DMA_1_RD_TH_ADDR                  0x04
#define AUDIO_BANK1_REG_DMA_1_RD_TH_REG_DMA_1_RD_TH_MASK  0xffff
#define AUDIO_BANK1_REG_DMA_1_RD_TH_REG_DMA_1_RD_TH_SHIFT 0

#define AUDIO_BANK1_REG_DMA_1_WR_TH_ADDR                  0x06
#define AUDIO_BANK1_REG_DMA_1_WR_TH_REG_DMA_1_WR_TH_MASK  0xffff
#define AUDIO_BANK1_REG_DMA_1_WR_TH_REG_DMA_1_WR_TH_SHIFT 0

#define AUDIO_BANK1_REG_DMA_1_RW_UPPER_TH_ADDR                        0x0C
#define AUDIO_BANK1_REG_DMA_1_RW_UPPER_TH_REG_DMA_1_RW_UPPER_TH_MASK  0xffff
#define AUDIO_BANK1_REG_DMA_1_RW_UPPER_TH_REG_DMA_1_RW_UPPER_TH_SHIFT 0

#define AUDIO_BANK1_REG_DMA_1_RW_LOWER_TH_ADDR                        0x0E
#define AUDIO_BANK1_REG_DMA_1_RW_LOWER_TH_REG_DMA_1_RW_LOWER_TH_MASK  0xffff
#define AUDIO_BANK1_REG_DMA_1_RW_LOWER_TH_REG_DMA_1_RW_LOWER_TH_SHIFT 0

#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_ADDR                               0x14
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_RW_DIFF_INT_CLR_MASK     0x400
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_RW_DIFF_INT_CLR_SHIFT    10
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_RW_DIFF_TRIG_MASK        0x100
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_RW_DIFF_TRIG_SHIFT       8
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_WR_TH_INT_CLR_MASK       0x20
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_WR_TH_INT_CLR_SHIFT      5
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_RD_TH_INT_CLR_MASK       0x10
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_RD_TH_INT_CLR_SHIFT      4
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_AWADDR_OFFSET_TRIG_MASK  0x2
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_AWADDR_OFFSET_TRIG_SHIFT 1
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_ARADDR_OFFSET_TRIG_MASK  0x1
#define AUDIO_BANK1_REG_FREQ_DIFF_INT_TRIG_REG_DMA_1_ARADDR_OFFSET_TRIG_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_0_ADDR                                  0x16
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_WR_UNDERRUN_INT_EN_MASK      0x8000
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_WR_UNDERRUN_INT_EN_SHIFT     15
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_WR_OVERRUN_INT_EN_MASK       0x4000
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_WR_OVERRUN_INT_EN_SHIFT      14
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_UNDERRUN_INT_EN_MASK      0x2000
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_UNDERRUN_INT_EN_SHIFT     13
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_OVERRUN_INT_EN_MASK       0x1000
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_OVERRUN_INT_EN_SHIFT      12
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_WR_FULL_INT_EN_MASK          0x800
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_WR_FULL_INT_EN_SHIFT         11
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_EMPTY_INT_EN_MASK         0x400
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_EMPTY_INT_EN_SHIFT        10
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_WR_FULL_FLAG_CLR_MASK        0x200
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_WR_FULL_FLAG_CLR_SHIFT       9
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_EMPTY_FLAG_CLR_MASK       0x100
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_EMPTY_FLAG_CLR_SHIFT      8
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_INVALID_DATA_MASK_MASK    0x80
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_INVALID_DATA_MASK_SHIFT   7
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_SEL_TES_BUS_MASK             0x40
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_SEL_TES_BUS_SHIFT            6
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_PRIORITY_KEEP_HIGH_MASK      0x10
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_PRIORITY_KEEP_HIGH_SHIFT     4
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_LEVEL_CNT_LIVE_MASK_MASK  0x4
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_RD_LEVEL_CNT_LIVE_MASK_SHIFT 2
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_ENABLE_MASK                  0x2
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_ENABLE_SHIFT                 1
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_SW_RST_DMA_MASK              0x1
#define AUDIO_BANK1_REG_DMA1_CTRL_0_REG_DMA1_SW_RST_DMA_SHIFT             0

#define AUDIO_BANK1_REG_DMA1_CTRL_1_ADDR                             0x18
#define AUDIO_BANK1_REG_DMA1_CTRL_1_REG_DMA1_RD_ENABLE_MASK          0x8000
#define AUDIO_BANK1_REG_DMA1_CTRL_1_REG_DMA1_RD_ENABLE_SHIFT         15
#define AUDIO_BANK1_REG_DMA1_CTRL_1_REG_DMA1_RD_INIT_MASK            0x4000
#define AUDIO_BANK1_REG_DMA1_CTRL_1_REG_DMA1_RD_INIT_SHIFT           14
#define AUDIO_BANK1_REG_DMA1_CTRL_1_REG_DMA1_RD_TRIG_MASK            0x2000
#define AUDIO_BANK1_REG_DMA1_CTRL_1_REG_DMA1_RD_TRIG_SHIFT           13
#define AUDIO_BANK1_REG_DMA1_CTRL_1_REG_DMA1_RD_LEVEL_CNT_MASK_MASK  0x1000
#define AUDIO_BANK1_REG_DMA1_CTRL_1_REG_DMA1_RD_LEVEL_CNT_MASK_SHIFT 12
#define AUDIO_BANK1_REG_DMA1_CTRL_1_REG_DMA1_RD_BASE_ADDR_LOW_MASK   0xfff
#define AUDIO_BANK1_REG_DMA1_CTRL_1_REG_DMA1_RD_BASE_ADDR_LOW_SHIFT  0

#define AUDIO_BANK1_REG_DMA1_CTRL_2_ADDR                             0x1A
#define AUDIO_BANK1_REG_DMA1_CTRL_2_REG_DMA1_RD_BASE_ADDR_HIGH_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_2_REG_DMA1_RD_BASE_ADDR_HIGH_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_3_ADDR                        0x1C
#define AUDIO_BANK1_REG_DMA1_CTRL_3_REG_DMA1_RD_BUFF_SIZE_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_3_REG_DMA1_RD_BUFF_SIZE_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_4_ADDR                   0x1E
#define AUDIO_BANK1_REG_DMA1_CTRL_4_REG_DMA1_RD_SIZE_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_4_REG_DMA1_RD_SIZE_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_5_ADDR                         0x20
#define AUDIO_BANK1_REG_DMA1_CTRL_5_REG_DMA1_RD_OVERRUN_TH_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_5_REG_DMA1_RD_OVERRUN_TH_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_6_ADDR                          0x22
#define AUDIO_BANK1_REG_DMA1_CTRL_6_REG_DMA1_RD_UNDERRUN_TH_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_6_REG_DMA1_RD_UNDERRUN_TH_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_7_ADDR                        0x24
#define AUDIO_BANK1_REG_DMA1_CTRL_7_REG_DMA1_RD_LEVEL_CNT_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_7_REG_DMA1_RD_LEVEL_CNT_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_8_ADDR                             0x26
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_TEST_BUS_MASK           0xff00
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_TEST_BUS_SHIFT          8
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_RD_LOCALBUF_EMPTY_MASK  0x80
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_RD_LOCALBUF_EMPTY_SHIFT 7
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_WR_LOCALBUF_FULL_MASK   0x40
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_WR_LOCALBUF_FULL_SHIFT  6
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_WR_FULL_FLAG_MASK       0x20
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_WR_FULL_FLAG_SHIFT      5
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_RD_EMPTY_FLAG_MASK      0x10
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_RD_EMPTY_FLAG_SHIFT     4
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_RD_OVERRUN_FLAG_MASK    0x8
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_RD_OVERRUN_FLAG_SHIFT   3
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_RD_UNDERRUN_FLAG_MASK   0x4
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_RD_UNDERRUN_FLAG_SHIFT  2
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_WR_OVERRUN_FLAG_MASK    0x2
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_WR_OVERRUN_FLAG_SHIFT   1
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_WR_UNDERRUN_FLAG_MASK   0x1
#define AUDIO_BANK1_REG_DMA1_CTRL_8_REG_DMA1_WR_UNDERRUN_FLAG_SHIFT  0

#define AUDIO_BANK1_REG_DMA1_CTRL_9_ADDR                             0x28
#define AUDIO_BANK1_REG_DMA1_CTRL_9_REG_DMA1_WR_ENABLE_MASK          0x8000
#define AUDIO_BANK1_REG_DMA1_CTRL_9_REG_DMA1_WR_ENABLE_SHIFT         15
#define AUDIO_BANK1_REG_DMA1_CTRL_9_REG_DMA1_WR_INIT_MASK            0x4000
#define AUDIO_BANK1_REG_DMA1_CTRL_9_REG_DMA1_WR_INIT_SHIFT           14
#define AUDIO_BANK1_REG_DMA1_CTRL_9_REG_DMA1_WR_TRIG_MASK            0x2000
#define AUDIO_BANK1_REG_DMA1_CTRL_9_REG_DMA1_WR_TRIG_SHIFT           13
#define AUDIO_BANK1_REG_DMA1_CTRL_9_REG_DMA1_WR_LEVEL_CNT_MASK_MASK  0x1000
#define AUDIO_BANK1_REG_DMA1_CTRL_9_REG_DMA1_WR_LEVEL_CNT_MASK_SHIFT 12
#define AUDIO_BANK1_REG_DMA1_CTRL_9_REG_DMA1_WR_BASE_ADDR_LOW_MASK   0xfff
#define AUDIO_BANK1_REG_DMA1_CTRL_9_REG_DMA1_WR_BASE_ADDR_LOW_SHIFT  0

#define AUDIO_BANK1_REG_DMA1_CTRL_10_ADDR                             0x2A
#define AUDIO_BANK1_REG_DMA1_CTRL_10_REG_DMA1_WR_BASE_ADDR_HIGH_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_10_REG_DMA1_WR_BASE_ADDR_HIGH_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_11_ADDR                        0x2C
#define AUDIO_BANK1_REG_DMA1_CTRL_11_REG_DMA1_WR_BUFF_SIZE_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_11_REG_DMA1_WR_BUFF_SIZE_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_12_ADDR                   0x2E
#define AUDIO_BANK1_REG_DMA1_CTRL_12_REG_DMA1_WR_SIZE_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_12_REG_DMA1_WR_SIZE_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_13_ADDR                         0x30
#define AUDIO_BANK1_REG_DMA1_CTRL_13_REG_DMA1_WR_OVERRUN_TH_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_13_REG_DMA1_WR_OVERRUN_TH_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_14_ADDR                          0x32
#define AUDIO_BANK1_REG_DMA1_CTRL_14_REG_DMA1_WR_UNDERRUN_TH_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_14_REG_DMA1_WR_UNDERRUN_TH_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_CTRL_15_ADDR                        0x34
#define AUDIO_BANK1_REG_DMA1_CTRL_15_REG_DMA1_WR_LEVEL_CNT_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_CTRL_15_REG_DMA1_WR_LEVEL_CNT_SHIFT 0

#define AUDIO_BANK1_REG_DMA_RD_LOCAL_BUFF_CTRL_ADDR                                      0x56
#define AUDIO_BANK1_REG_DMA_RD_LOCAL_BUFF_CTRL_REG_DMA1_AO_LOCALBUF_EMPTY_MODE_MASK      0x300
#define AUDIO_BANK1_REG_DMA_RD_LOCAL_BUFF_CTRL_REG_DMA1_AO_LOCALBUF_EMPTY_MODE_SHIFT     8
#define AUDIO_BANK1_REG_DMA_RD_LOCAL_BUFF_CTRL_REG_DMA1_RD_EMPTY_FLAG_TH_MASK            0xf0
#define AUDIO_BANK1_REG_DMA_RD_LOCAL_BUFF_CTRL_REG_DMA1_RD_EMPTY_FLAG_TH_SHIFT           4
#define AUDIO_BANK1_REG_DMA_RD_LOCAL_BUFF_CTRL_REG_DMA1_WR_LOCAL_BUFF_FULL_INT_EN_MASK   0x8
#define AUDIO_BANK1_REG_DMA_RD_LOCAL_BUFF_CTRL_REG_DMA1_WR_LOCAL_BUFF_FULL_INT_EN_SHIFT  3
#define AUDIO_BANK1_REG_DMA_RD_LOCAL_BUFF_CTRL_REG_DMA1_RD_LOCAL_BUFF_EMPTY_INT_EN_MASK  0x2
#define AUDIO_BANK1_REG_DMA_RD_LOCAL_BUFF_CTRL_REG_DMA1_RD_LOCAL_BUFF_EMPTY_INT_EN_SHIFT 1
#define AUDIO_BANK1_REG_DMA_RD_LOCAL_BUFF_CTRL_REG_RD_LEVEL_CNT_FORCE_EN_MASK            0x1
#define AUDIO_BANK1_REG_DMA_RD_LOCAL_BUFF_CTRL_REG_RD_LEVEL_CNT_FORCE_EN_SHIFT           0

#define AUDIO_BANK1_REG_DMA_WR_AFTER_RD_ADDR                        0x60
#define AUDIO_BANK1_REG_DMA_WR_AFTER_RD_REG_DMA1_FS_TUNING_EN_MASK  0x4000
#define AUDIO_BANK1_REG_DMA_WR_AFTER_RD_REG_DMA1_FS_TUNING_EN_SHIFT 14
#define AUDIO_BANK1_REG_DMA_WR_AFTER_RD_DMA_1_RW_DIFF_INT_EN_MASK   0x1000
#define AUDIO_BANK1_REG_DMA_WR_AFTER_RD_DMA_1_RW_DIFF_INT_EN_SHIFT  12
#define AUDIO_BANK1_REG_DMA_WR_AFTER_RD_REG_DMA_1_WR_TH_EN_MASK     0x200
#define AUDIO_BANK1_REG_DMA_WR_AFTER_RD_REG_DMA_1_WR_TH_EN_SHIFT    9
#define AUDIO_BANK1_REG_DMA_WR_AFTER_RD_REG_DMA_1_RD_TH_EN_MASK     0x100
#define AUDIO_BANK1_REG_DMA_WR_AFTER_RD_REG_DMA_1_RD_TH_EN_SHIFT    8
#define AUDIO_BANK1_REG_DMA_WR_AFTER_RD_REG_DMA1_WR_AFTER_RD_MASK   0x1
#define AUDIO_BANK1_REG_DMA_WR_AFTER_RD_REG_DMA1_WR_AFTER_RD_SHIFT  0

#define AUDIO_BANK1_REG_DMA1_DELAY_TIME_LOW_ADDR                          0x62
#define AUDIO_BANK1_REG_DMA1_DELAY_TIME_LOW_REG_DMA1_RD_DLY_NUM_LOW_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_DELAY_TIME_LOW_REG_DMA1_RD_DLY_NUM_LOW_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_DELAY_TIME_HIGH_ADDR                           0x64
#define AUDIO_BANK1_REG_DMA1_DELAY_TIME_HIGH_REG_DMA1_RD_DLY_NUM_HIGH_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_DELAY_TIME_HIGH_REG_DMA1_RD_DLY_NUM_HIGH_SHIFT 0

#define AUDIO_BANK1_REG_DMA_1_AWADDR_OFFSET_ADDR                          0x6A
#define AUDIO_BANK1_REG_DMA_1_AWADDR_OFFSET_REG_DMA_1_AWADDR_OFFSET_MASK  0xffff
#define AUDIO_BANK1_REG_DMA_1_AWADDR_OFFSET_REG_DMA_1_AWADDR_OFFSET_SHIFT 0

#define AUDIO_BANK1_REG_DMA_1_ARADDR_OFFSET_ADDR                          0x6E
#define AUDIO_BANK1_REG_DMA_1_ARADDR_OFFSET_REG_DMA_1_ARADDR_OFFSET_MASK  0xffff
#define AUDIO_BANK1_REG_DMA_1_ARADDR_OFFSET_REG_DMA_1_ARADDR_OFFSET_SHIFT 0

#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_ADDR                  0x7A
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_RD_SEL_MASK  0xc0
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_RD_SEL_SHIFT 6
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_RD_MASK      0x20
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_RD_SHIFT     5
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_RD_EN_MASK   0x10
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_RD_EN_SHIFT  4
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_WR_SEL_MASK  0xc
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_WR_SEL_SHIFT 2
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_WR_MASK      0x2
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_WR_SHIFT     1
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_WR_EN_MASK   0x1
#define AUDIO_BANK1_REG_DMA_TEST_CTRL0_DMA_TEST_WR_EN_SHIFT  0

#define AUDIO_BANK1_REG_DMA_TEST_CTRL1_ADDR                    0x7C
#define AUDIO_BANK1_REG_DMA_TEST_CTRL1_DMA_WR_DATA_L_MUX_MASK  0xffff
#define AUDIO_BANK1_REG_DMA_TEST_CTRL1_DMA_WR_DATA_L_MUX_SHIFT 0

#define AUDIO_BANK1_REG_DMA_TEST_CTRL2_ADDR                    0x7E
#define AUDIO_BANK1_REG_DMA_TEST_CTRL2_DMA_WR_DATA_R_MUX_MASK  0xffff
#define AUDIO_BANK1_REG_DMA_TEST_CTRL2_DMA_WR_DATA_R_MUX_SHIFT 0

#define AUDIO_BANK1_REG_DMA_TEST_CTRL3_ADDR                     0x80
#define AUDIO_BANK1_REG_DMA_TEST_CTRL3_RIU_DMA_TEST_CTRL3_MASK  0xffff
#define AUDIO_BANK1_REG_DMA_TEST_CTRL3_RIU_DMA_TEST_CTRL3_SHIFT 0

#define AUDIO_BANK1_REG_DMA_TEST_CTRL4_ADDR                     0x82
#define AUDIO_BANK1_REG_DMA_TEST_CTRL4_RIU_DMA_TEST_CTRL4_MASK  0xffff
#define AUDIO_BANK1_REG_DMA_TEST_CTRL4_RIU_DMA_TEST_CTRL4_SHIFT 0

#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_ADDR                          0x84
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_EN_DMA1_MASK     0x8000
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_EN_DMA1_SHIFT    15
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_L_DMA1_MASK      0x4000
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_L_DMA1_SHIFT     14
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_R_DMA1_MASK      0x2000
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_R_DMA1_SHIFT     13
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_RD_WR_DMA1_MASK  0x1000
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_RD_WR_DMA1_SHIFT 12
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_DMA_TEST_SEL_H_DMA1_MASK  0x800
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_DMA_TEST_SEL_H_DMA1_SHIFT 11
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_DMA_TEST_SEL_DMA1_MASK    0x700
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_DMA_TEST_SEL_DMA1_SHIFT   8
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_GAIN_DMA1_MASK   0xf0
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_GAIN_DMA1_SHIFT  4
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_FREQ_DMA1_MASK   0xf
#define AUDIO_BANK1_REG_DMA_TEST_CTRL5_REG_SINE_GEN_FREQ_DMA1_SHIFT  0

#define AUDIO_BANK1_REG_DMA_TEST_CTRL7_ADDR                                 0x88
#define AUDIO_BANK1_REG_DMA_TEST_CTRL7_REG_DMA1_RD_MONO_MASK                0x8000
#define AUDIO_BANK1_REG_DMA_TEST_CTRL7_REG_DMA1_RD_MONO_SHIFT               15
#define AUDIO_BANK1_REG_DMA_TEST_CTRL7_REG_DMA1_WR_MONO_MASK                0x4000
#define AUDIO_BANK1_REG_DMA_TEST_CTRL7_REG_DMA1_WR_MONO_SHIFT               14
#define AUDIO_BANK1_REG_DMA_TEST_CTRL7_REG_DMA1_RD_MONO_COPY_MASK           0x2000
#define AUDIO_BANK1_REG_DMA_TEST_CTRL7_REG_DMA1_RD_MONO_COPY_SHIFT          13
#define AUDIO_BANK1_REG_DMA_TEST_CTRL7_REG_DMA_1_SINE_GEN_GAIN_EXTEND_MASK  0x4
#define AUDIO_BANK1_REG_DMA_TEST_CTRL7_REG_DMA_1_SINE_GEN_GAIN_EXTEND_SHIFT 2
#define AUDIO_BANK1_REG_DMA_TEST_CTRL7_REG_DMA1_RD_WR_ENABLE_MASK           0x1
#define AUDIO_BANK1_REG_DMA_TEST_CTRL7_REG_DMA1_RD_WR_ENABLE_SHIFT          0

#define AUDIO_BANK1_REG_DMA_TEST_CTRL8_ADDR                          0x8A
#define AUDIO_BANK1_REG_DMA_TEST_CTRL8_REG_DMA1_WR_BASE_ADDR_H_MASK  0xf0
#define AUDIO_BANK1_REG_DMA_TEST_CTRL8_REG_DMA1_WR_BASE_ADDR_H_SHIFT 4
#define AUDIO_BANK1_REG_DMA_TEST_CTRL8_REG_DMA1_RD_BASE_ADDR_H_MASK  0xf
#define AUDIO_BANK1_REG_DMA_TEST_CTRL8_REG_DMA1_RD_BASE_ADDR_H_SHIFT 0

#define AUDIO_BANK1_REG_DMA_TEST_CTRL9_ADDR                    0x8C
#define AUDIO_BANK1_REG_DMA_TEST_CTRL9_REG_DMA1_RD_R_SEL_MASK  0x38
#define AUDIO_BANK1_REG_DMA_TEST_CTRL9_REG_DMA1_RD_R_SEL_SHIFT 3
#define AUDIO_BANK1_REG_DMA_TEST_CTRL9_REG_DMA1_RD_L_SEL_MASK  0x7
#define AUDIO_BANK1_REG_DMA_TEST_CTRL9_REG_DMA1_RD_L_SEL_SHIFT 0

#define AUDIO_BANK1_REG_DMA1_FS_TUNING_ADDR                     0x90
#define AUDIO_BANK1_REG_DMA1_FS_TUNING_REG_DMA1_FS_TUNING_MASK  0xffff
#define AUDIO_BANK1_REG_DMA1_FS_TUNING_REG_DMA1_FS_TUNING_SHIFT 0

#define AUDIO_BANK1_REG_DMA12_INT_STATUS_ADDR                           0x94
#define AUDIO_BANK1_REG_DMA12_INT_STATUS_DMA_1_WR_TH_INT_STATUS_MASK    0x20
#define AUDIO_BANK1_REG_DMA12_INT_STATUS_DMA_1_WR_TH_INT_STATUS_SHIFT   5
#define AUDIO_BANK1_REG_DMA12_INT_STATUS_DMA_1_RD_TH_INT_STATUS_MASK    0x10
#define AUDIO_BANK1_REG_DMA12_INT_STATUS_DMA_1_RD_TH_INT_STATUS_SHIFT   4
#define AUDIO_BANK1_REG_DMA12_INT_STATUS_DMA_1_RW_DIFF_INT_STATUS_MASK  0x1
#define AUDIO_BANK1_REG_DMA12_INT_STATUS_DMA_1_RW_DIFF_INT_STATUS_SHIFT 0

#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_00_ADDR                       0x96
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_00_REG_DMA_W1_CH23_SEL_MASK   0xf000
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_00_REG_DMA_W1_CH23_SEL_SHIFT  12
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_00_REG_DMA_W1_CH01_SEL_MASK   0xf00
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_00_REG_DMA_W1_CH01_SEL_SHIFT  8
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_00_REG_DMA_W1_VALID_SEL_MASK  0xe0
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_00_REG_DMA_W1_VALID_SEL_SHIFT 5
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_00_REG_DMA_W1_CH_MODE_MASK    0x1c
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_00_REG_DMA_W1_CH_MODE_SHIFT   2
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_00_REG_DMA_W1_NEW_MODE_MASK   0x3
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_00_REG_DMA_W1_NEW_MODE_SHIFT  0

#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_ADDR                                       0x9A
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_DMA_MCH_32B_DBG_1_MASK                 0x8000
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_DMA_MCH_32B_DBG_1_SHIFT                15
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_DMA_W1_BIT_MODE_MASK                   0x4000
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_DMA_W1_BIT_MODE_SHIFT                  14
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_DMA_MCH_32B_ENABLE_1_MASK              0x2000
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_DMA_MCH_32B_ENABLE_1_SHIFT             13
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_I2S_TDM_RX1_AFIFO_READ_VALID_SEL_MASK  0x300
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_I2S_TDM_RX1_AFIFO_READ_VALID_SEL_SHIFT 8
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_DMA1_READ_VALID_I2STX_SEL_MASK         0x40
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_DMA1_READ_VALID_I2STX_SEL_SHIFT        6
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_DMA1_READ_VALID_SEL_MASK               0xc
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_DMA1_READ_VALID_SEL_SHIFT              2
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_I2S_TDM_RX_AFIFO_READ_VALID_SEL_MASK   0x3
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_02_REG_I2S_TDM_RX_AFIFO_READ_VALID_SEL_SHIFT  0

#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_03_ADDR                      0x9C
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_03_REG_DMA_W1_CH67_SEL_MASK  0xf0
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_03_REG_DMA_W1_CH67_SEL_SHIFT 4
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_03_REG_DMA_W1_CH45_SEL_MASK  0xf
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_03_REG_DMA_W1_CH45_SEL_SHIFT 0

#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_04_ADDR                      0x9E
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_04_REG_DMA_W1_CHAB_SEL_MASK  0xf0
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_04_REG_DMA_W1_CHAB_SEL_SHIFT 4
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_04_REG_DMA_W1_CH89_SEL_MASK  0xf
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_04_REG_DMA_W1_CH89_SEL_SHIFT 0

#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_05_ADDR                      0xA0
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_05_REG_DMA_W1_CHEF_SEL_MASK  0xf0
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_05_REG_DMA_W1_CHEF_SEL_SHIFT 4
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_05_REG_DMA_W1_CHCD_SEL_MASK  0xf
#define AUDIO_BANK1_REG_DMA_SOURCE_CFG_05_REG_DMA_W1_CHCD_SEL_SHIFT 0

#define AUDIO_BANK1_REG_AU_SYS_CTRL2_ADDR                    0xA2
#define AUDIO_BANK1_REG_AU_SYS_CTRL2_REG_RESET_DMA_MCH_MASK  0x2000
#define AUDIO_BANK1_REG_AU_SYS_CTRL2_REG_RESET_DMA_MCH_SHIFT 13

#define AUDIO_BANK1_REG_DMA1_FS_TUNING_CFG_ADDR                                   0xA4
#define AUDIO_BANK1_REG_DMA1_FS_TUNING_CFG_REG_DMA1_FS_TUNING_POWER_THR_EXP_MASK  0xf800
#define AUDIO_BANK1_REG_DMA1_FS_TUNING_CFG_REG_DMA1_FS_TUNING_POWER_THR_EXP_SHIFT 11
#define AUDIO_BANK1_REG_DMA1_FS_TUNING_CFG_REG_DMA1_FS_TUNING_EXP_MASK            0x1ff
#define AUDIO_BANK1_REG_DMA1_FS_TUNING_CFG_REG_DMA1_FS_TUNING_EXP_SHIFT           0

#endif
