/*
 * audio_bank4_sw_reg_define.h - Sigmastar
 *
 * Copyright (c) [2019~2022] SigmaStar Technology.
 *
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details.
 *
 */

#ifndef __JM_AUDIO_BANK4_SW_REG_DEFINE_H__
#define __JM_AUDIO_BANK4_SW_REG_DEFINE_H__

#define AUDIO_BANK4_REG_ENABLE_CTRL_ADDR                   0x00
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_TIME_GEN_EN_MASK   0x8000
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_TIME_GEN_EN_SHIFT  15
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_INIT_SRAM_EN_MASK  0x4000
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_INIT_SRAM_EN_SHIFT 14
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_BP_ADC_HPF2_MASK   0x800
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_BP_ADC_HPF2_SHIFT  11
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_BP_ADC_HPF1_MASK   0x400
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_BP_ADC_HPF1_SHIFT  10
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_EN_INT_1_MASK      0x100
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_EN_INT_1_SHIFT     8
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_EN_DEC_1_MASK      0x40
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_EN_DEC_1_SHIFT     6
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_EN_DEC_3_MASK      0x10
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_EN_DEC_3_SHIFT     4
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_EN_CODEC_MASK      0x1
#define AUDIO_BANK4_REG_ENABLE_CTRL_REG_EN_CODEC_SHIFT     0

#define AUDIO_BANK4_REG_SR0_SEL_ADDR                0x02
#define AUDIO_BANK4_REG_SR0_SEL_REG_CIC_1_SEL_MASK  0xc000
#define AUDIO_BANK4_REG_SR0_SEL_REG_CIC_1_SEL_SHIFT 14
#define AUDIO_BANK4_REG_SR0_SEL_REG_CIC_3_SEL_MASK  0xc00
#define AUDIO_BANK4_REG_SR0_SEL_REG_CIC_3_SEL_SHIFT 10
#define AUDIO_BANK4_REG_SR0_SEL_REG_CODEC_SEL_MASK  0x300
#define AUDIO_BANK4_REG_SR0_SEL_REG_CODEC_SEL_SHIFT 8
#define AUDIO_BANK4_REG_SR0_SEL_REG_SRC1_SEL_MASK   0xf0
#define AUDIO_BANK4_REG_SR0_SEL_REG_SRC1_SEL_SHIFT  4

#define AUDIO_BANK4_REG_SR1_SEL_ADDR                  0x04
#define AUDIO_BANK4_REG_SR1_SEL_REG_RESET_AU_MASK     0x8000
#define AUDIO_BANK4_REG_SR1_SEL_REG_RESET_AU_SHIFT    15
#define AUDIO_BANK4_REG_SR1_SEL_REG_RESET_DPGA_MASK   0x2000
#define AUDIO_BANK4_REG_SR1_SEL_REG_RESET_DPGA_SHIFT  13
#define AUDIO_BANK4_REG_SR1_SEL_REG_RESET_AB_MASK     0x1000
#define AUDIO_BANK4_REG_SR1_SEL_REG_RESET_AB_SHIFT    12
#define AUDIO_BANK4_REG_SR1_SEL_REG_RESET_SDM_MASK    0x400
#define AUDIO_BANK4_REG_SR1_SEL_REG_RESET_SDM_SHIFT   10
#define AUDIO_BANK4_REG_SR1_SEL_REG_RESET_SYNTH_MASK  0x100
#define AUDIO_BANK4_REG_SR1_SEL_REG_RESET_SYNTH_SHIFT 8
#define AUDIO_BANK4_REG_SR1_SEL_REG_ADC_RSEL_MASK     0x8
#define AUDIO_BANK4_REG_SR1_SEL_REG_ADC_RSEL_SHIFT    3

#define AUDIO_BANK4_REG_MUX0_SEL_ADDR                    0x08
#define AUDIO_BANK4_REG_MUX0_SEL_REG_MMC1_MMC3_SEL_MASK  0x1
#define AUDIO_BANK4_REG_MUX0_SEL_REG_MMC1_MMC3_SEL_SHIFT 0

#define AUDIO_BANK4_REG_MUX1_SEL_ADDR                0x0A
#define AUDIO_BANK4_REG_MUX1_SEL_REG_ADC_HPF_N_MASK  0xf000
#define AUDIO_BANK4_REG_MUX1_SEL_REG_ADC_HPF_N_SHIFT 12
#define AUDIO_BANK4_REG_MUX1_SEL_REG_SAT_SEL_MASK    0x800
#define AUDIO_BANK4_REG_MUX1_SEL_REG_SAT_SEL_SHIFT   11

#define AUDIO_BANK4_REG_MUX2_SEL_ADDR                   0x0C
#define AUDIO_BANK4_REG_MUX2_SEL_REG_TEST_BUS_SEL_MASK  0x200
#define AUDIO_BANK4_REG_MUX2_SEL_REG_TEST_BUS_SEL_SHIFT 9

#define AUDIO_BANK4_REG_SYNTH_CTRL_ADDR                   0x10
#define AUDIO_BANK4_REG_SYNTH_CTRL_REG_AUTO_UPD_DIS_MASK  0x400
#define AUDIO_BANK4_REG_SYNTH_CTRL_REG_AUTO_UPD_DIS_SHIFT 10
#define AUDIO_BANK4_REG_SYNTH_CTRL_REG_CMP_CIC_MASK       0x7f
#define AUDIO_BANK4_REG_SYNTH_CTRL_REG_CMP_CIC_SHIFT      0

#define AUDIO_BANK4_REG_COUNTER1_CTRL_LOW_ADDR                         0x20
#define AUDIO_BANK4_REG_COUNTER1_CTRL_LOW_REG_COUNTER1_LEVEL_LOW_MASK  0xffff
#define AUDIO_BANK4_REG_COUNTER1_CTRL_LOW_REG_COUNTER1_LEVEL_LOW_SHIFT 0

#define AUDIO_BANK4_REG_COUNTER1_CTRL_HIGH_ADDR                          0x22
#define AUDIO_BANK4_REG_COUNTER1_CTRL_HIGH_REG_COUNTER1_TRIG_MASK        0x8000
#define AUDIO_BANK4_REG_COUNTER1_CTRL_HIGH_REG_COUNTER1_TRIG_SHIFT       15
#define AUDIO_BANK4_REG_COUNTER1_CTRL_HIGH_REG_COUNTER_SEL_MASK          0x7000
#define AUDIO_BANK4_REG_COUNTER1_CTRL_HIGH_REG_COUNTER_SEL_SHIFT         12
#define AUDIO_BANK4_REG_COUNTER1_CTRL_HIGH_REG_COUNTER1_LEVEL_HIGH_MASK  0xfff
#define AUDIO_BANK4_REG_COUNTER1_CTRL_HIGH_REG_COUNTER1_LEVEL_HIGH_SHIFT 0

#define AUDIO_BANK4_REG_COUNTER1_STATUS_LOW_ADDR                         0x24
#define AUDIO_BANK4_REG_COUNTER1_STATUS_LOW_REG_COUNTER1_VALUE_LOW_MASK  0xffff
#define AUDIO_BANK4_REG_COUNTER1_STATUS_LOW_REG_COUNTER1_VALUE_LOW_SHIFT 0

#define AUDIO_BANK4_REG_COUNTER1_STATUS_HIGH_ADDR                          0x26
#define AUDIO_BANK4_REG_COUNTER1_STATUS_HIGH_REG_COUNTER1_FLAG_MASK        0x8000
#define AUDIO_BANK4_REG_COUNTER1_STATUS_HIGH_REG_COUNTER1_FLAG_SHIFT       15
#define AUDIO_BANK4_REG_COUNTER1_STATUS_HIGH_REG_COUNTER1_BUSY_MASK        0x4000
#define AUDIO_BANK4_REG_COUNTER1_STATUS_HIGH_REG_COUNTER1_BUSY_SHIFT       14
#define AUDIO_BANK4_REG_COUNTER1_STATUS_HIGH_REG_COUNTER1_VALUE_HIGH_MASK  0xfff
#define AUDIO_BANK4_REG_COUNTER1_STATUS_HIGH_REG_COUNTER1_VALUE_HIGH_SHIFT 0

#define AUDIO_BANK4_REG_FREQ_DIFF_INT_TH_ADDR                0x28
#define AUDIO_BANK4_REG_FREQ_DIFF_INT_TH_DET_GE_REF_TH_MASK  0xff00
#define AUDIO_BANK4_REG_FREQ_DIFF_INT_TH_DET_GE_REF_TH_SHIFT 8
#define AUDIO_BANK4_REG_FREQ_DIFF_INT_TH_REF_GE_DET_TH_MASK  0xff
#define AUDIO_BANK4_REG_FREQ_DIFF_INT_TH_REF_GE_DET_TH_SHIFT 0

#define AUDIO_BANK4_REG_PAD_TEST_ADDR                             0x30
#define AUDIO_BANK4_REG_PAD_TEST_ENABLE_INT_TEST_MODE_MASK        0x8000
#define AUDIO_BANK4_REG_PAD_TEST_ENABLE_INT_TEST_MODE_SHIFT       15
#define AUDIO_BANK4_REG_PAD_TEST_INT_TEST_MODE_VOLUE_TO_MMP_MASK  0x4000
#define AUDIO_BANK4_REG_PAD_TEST_INT_TEST_MODE_VOLUE_TO_MMP_SHIFT 14
#define AUDIO_BANK4_REG_PAD_TEST_REG_PAD_TEST_11_6_MASK           0xfc0
#define AUDIO_BANK4_REG_PAD_TEST_REG_PAD_TEST_11_6_SHIFT          6
#define AUDIO_BANK4_REG_PAD_TEST_REG_PAD_TEST_5_0_MASK            0x3f
#define AUDIO_BANK4_REG_PAD_TEST_REG_PAD_TEST_5_0_SHIFT           0

#define AUDIO_BANK4_REG_PAD0_CFG_ADDR                        0x32
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_MCK_FSEL_MASK         0x8000
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_MCK_FSEL_SHIFT        15
#define AUDIO_BANK4_REG_PAD0_CFG_PAD_DBB_TEST_MASK           0x4000
#define AUDIO_BANK4_REG_PAD0_CFG_PAD_DBB_TEST_SHIFT          14
#define AUDIO_BANK4_REG_PAD0_CFG_PAD_OUTPUT_TEST_MASK        0x2000
#define AUDIO_BANK4_REG_PAD0_CFG_PAD_OUTPUT_TEST_SHIFT       13
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_I2S_TDM_LOOP_MASK     0x1000
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_I2S_TDM_LOOP_SHIFT    12
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_DAAD2_LOOP_MASK       0x800
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_DAAD2_LOOP_SHIFT      11
#define AUDIO_BANK4_REG_PAD0_CFG_REG_I2S_TRX_SDI_SEL_MASK    0x400
#define AUDIO_BANK4_REG_PAD0_CFG_REG_I2S_TRX_SDI_SEL_SHIFT   10
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_I2S_LOOP_MASK         0x100
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_I2S_LOOP_SHIFT        8
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_DAAD_LOOP_MASK        0x80
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_DAAD_LOOP_SHIFT       7
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_TEST_SEL_MASK         0x40
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_TEST_SEL_SHIFT        6
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_I2S_TRX_MCK_INV_MASK  0x10
#define AUDIO_BANK4_REG_PAD0_CFG_CODEC_I2S_TRX_MCK_INV_SHIFT 4

#define AUDIO_BANK4_REG_PAD1_CFG_ADDR                            0x34
#define AUDIO_BANK4_REG_PAD1_CFG_REG_PAD_OEN_SEL_MASK            0x8000
#define AUDIO_BANK4_REG_PAD1_CFG_REG_PAD_OEN_SEL_SHIFT           15
#define AUDIO_BANK4_REG_PAD1_CFG_REG_CODEC_I2S_TRX_WCK_OEN_MASK  0x100
#define AUDIO_BANK4_REG_PAD1_CFG_REG_CODEC_I2S_TRX_WCK_OEN_SHIFT 8
#define AUDIO_BANK4_REG_PAD1_CFG_REG_CODEC_I2S_TRX_BCK_OEN_MASK  0x80
#define AUDIO_BANK4_REG_PAD1_CFG_REG_CODEC_I2S_TRX_BCK_OEN_SHIFT 7
#define AUDIO_BANK4_REG_PAD1_CFG_REG_CODEC_I2S_TRX_SDI_OEN_MASK  0x40
#define AUDIO_BANK4_REG_PAD1_CFG_REG_CODEC_I2S_TRX_SDI_OEN_SHIFT 6
#define AUDIO_BANK4_REG_PAD1_CFG_REG_CODEC_I2S_TRX_SDO_OEN_MASK  0x20
#define AUDIO_BANK4_REG_PAD1_CFG_REG_CODEC_I2S_TRX_SDO_OEN_SHIFT 5

#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_00_ADDR                                 0x40
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_00_REG_SEL_CLK_NF_SYNTH_RX_REF_MASK     0xc0
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_00_REG_SEL_CLK_NF_SYNTH_RX_REF_SHIFT    6
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_00_REG_INV_CLK_NF_SYNTH_RX_REF_MASK     0x20
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_00_REG_INV_CLK_NF_SYNTH_RX_REF_SHIFT    5
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_00_REG_ENABLE_CLK_NF_SYNTH_RX_REF_MASK  0x10
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_00_REG_ENABLE_CLK_NF_SYNTH_RX_REF_SHIFT 4
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_00_REG_CODEC_RX_BCK_NF_SYNTH_TRIG_MASK  0x4
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_00_REG_CODEC_RX_BCK_NF_SYNTH_TRIG_SHIFT 2
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_00_REG_CODEC_RX_BCK_EN_TIME_GEN_MASK    0x1
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_00_REG_CODEC_RX_BCK_EN_TIME_GEN_SHIFT   0

#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_01_ADDR                                      0x42
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_01_REG_CODEC_RX_BCK_SYNTH_NF_VALUE_LOW_MASK  0xffff
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_01_REG_CODEC_RX_BCK_SYNTH_NF_VALUE_LOW_SHIFT 0

#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_02_ADDR                                       0x44
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_02_REG_CODEC_RX_BCK_SYNTH_NF_VALUE_HIGH_MASK  0xffff
#define AUDIO_BANK4_REG_NF_SYNTH_RX_BCK_02_REG_CODEC_RX_BCK_SYNTH_NF_VALUE_HIGH_SHIFT 0

#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_00_ADDR                                 0x46
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_00_REG_SEL_CLK_NF_SYNTH_TX_REF_MASK     0xc0
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_00_REG_SEL_CLK_NF_SYNTH_TX_REF_SHIFT    6
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_00_REG_INV_CLK_NF_SYNTH_TX_REF_MASK     0x20
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_00_REG_INV_CLK_NF_SYNTH_TX_REF_SHIFT    5
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_00_REG_ENABLE_CLK_NF_SYNTH_TX_REF_MASK  0x10
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_00_REG_ENABLE_CLK_NF_SYNTH_TX_REF_SHIFT 4
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_00_REG_CODEC_TX_BCK_NF_SYNTH_TRIG_MASK  0x4
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_00_REG_CODEC_TX_BCK_NF_SYNTH_TRIG_SHIFT 2
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_00_REG_CODEC_TX_BCK_EN_TIME_GEN_MASK    0x1
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_00_REG_CODEC_TX_BCK_EN_TIME_GEN_SHIFT   0

#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_01_ADDR                                      0x48
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_01_REG_CODEC_TX_BCK_SYNTH_NF_VALUE_LOW_MASK  0xffff
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_01_REG_CODEC_TX_BCK_SYNTH_NF_VALUE_LOW_SHIFT 0

#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_02_ADDR                                       0x4A
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_02_REG_CODEC_TX_BCK_SYNTH_NF_VALUE_HIGH_MASK  0xffff
#define AUDIO_BANK4_REG_NF_SYNTH_TX_BCK_02_REG_CODEC_TX_BCK_SYNTH_NF_VALUE_HIGH_SHIFT 0

#define AUDIO_BANK4_REG_NF_SYNTH_MCK_00_ADDR                              0x4C
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_00_REG_SEL_CLK_NF_SYNTH_REF_MASK     0xc0
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_00_REG_SEL_CLK_NF_SYNTH_REF_SHIFT    6
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_00_REG_INV_CLK_NF_SYNTH_REF_MASK     0x20
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_00_REG_INV_CLK_NF_SYNTH_REF_SHIFT    5
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_00_REG_ENABLE_CLK_NF_SYNTH_REF_MASK  0x10
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_00_REG_ENABLE_CLK_NF_SYNTH_REF_SHIFT 4
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_00_REG_CODEC_MCK_NF_SYNTH_TRIG_MASK  0x4
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_00_REG_CODEC_MCK_NF_SYNTH_TRIG_SHIFT 2
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_00_REG_CODEC_MCK_EN_TIME_GEN_MASK    0x1
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_00_REG_CODEC_MCK_EN_TIME_GEN_SHIFT   0

#define AUDIO_BANK4_REG_NF_SYNTH_MCK_01_ADDR                                   0x4E
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_01_REG_CODEC_MCK_SYNTH_NF_VALUE_LOW_MASK  0xffff
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_01_REG_CODEC_MCK_SYNTH_NF_VALUE_LOW_SHIFT 0

#define AUDIO_BANK4_REG_NF_SYNTH_MCK_02_ADDR                                    0x50
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_02_REG_CODEC_MCK_EXPAND_VALUE_MASK         0xff00
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_02_REG_CODEC_MCK_EXPAND_VALUE_SHIFT        8
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_02_REG_CODEC_MCK_SYNTH_NF_VALUE_HIGH_MASK  0xff
#define AUDIO_BANK4_REG_NF_SYNTH_MCK_02_REG_CODEC_MCK_SYNTH_NF_VALUE_HIGH_SHIFT 0

#define AUDIO_BANK4_REG_CKG_TEST_MD_ADDR                   0x52
#define AUDIO_BANK4_REG_CKG_TEST_MD_REG_TEST_MUX_SEL_MASK  0x1f0
#define AUDIO_BANK4_REG_CKG_TEST_MD_REG_TEST_MUX_SEL_SHIFT 4
#define AUDIO_BANK4_REG_CKG_TEST_MD_REG_TEST_CLK_SEL_MASK  0xf
#define AUDIO_BANK4_REG_CKG_TEST_MD_REG_TEST_CLK_SEL_SHIFT 0

#define AUDIO_BANK4_REG_MMC1_MUX_ADDR                 0x54
#define AUDIO_BANK4_REG_MMC1_MUX_REG_MMC1_L_MUX_MASK  0x7f00
#define AUDIO_BANK4_REG_MMC1_MUX_REG_MMC1_L_MUX_SHIFT 8
#define AUDIO_BANK4_REG_MMC1_MUX_REG_MMC1_R_MUX_MASK  0x7f
#define AUDIO_BANK4_REG_MMC1_MUX_REG_MMC1_R_MUX_SHIFT 0

#define AUDIO_BANK4_REG_SRC1_MIXER0_CTL_ADDR                        0x56
#define AUDIO_BANK4_REG_SRC1_MIXER0_CTL_REG_MMC1_MIXER0_INV_L_MASK  0x100
#define AUDIO_BANK4_REG_SRC1_MIXER0_CTL_REG_MMC1_MIXER0_INV_L_SHIFT 8
#define AUDIO_BANK4_REG_SRC1_MIXER0_CTL_REG_MMC1_MIXER0_INV_R_MASK  0x1
#define AUDIO_BANK4_REG_SRC1_MIXER0_CTL_REG_MMC1_MIXER0_INV_R_SHIFT 0

#define AUDIO_BANK4_REG_INT_EN_ADDR                  0x5A
#define AUDIO_BANK4_REG_INT_EN_REG_TEST_BUS_EN_MASK  0x8000
#define AUDIO_BANK4_REG_INT_EN_REG_TEST_BUS_EN_SHIFT 15
#define AUDIO_BANK4_REG_INT_EN_REG_INT_EN6_MASK      0x40
#define AUDIO_BANK4_REG_INT_EN_REG_INT_EN6_SHIFT     6
#define AUDIO_BANK4_REG_INT_EN_REG_INT_EN5_MASK      0x20
#define AUDIO_BANK4_REG_INT_EN_REG_INT_EN5_SHIFT     5
#define AUDIO_BANK4_REG_INT_EN_REG_INT_EN4_MASK      0x10
#define AUDIO_BANK4_REG_INT_EN_REG_INT_EN4_SHIFT     4
#define AUDIO_BANK4_REG_INT_EN_REG_INT_EN1_MASK      0x2
#define AUDIO_BANK4_REG_INT_EN_REG_INT_EN1_SHIFT     1
#define AUDIO_BANK4_REG_INT_EN_REG_INT_EN0_MASK      0x1
#define AUDIO_BANK4_REG_INT_EN_REG_INT_EN0_SHIFT     0

#define AUDIO_BANK4_REG_RESERVED_0X1E_ADDR            0x5C
#define AUDIO_BANK4_REG_RESERVED_0X1E_DFT_DUMMY_MASK  0xffff
#define AUDIO_BANK4_REG_RESERVED_0X1E_DFT_DUMMY_SHIFT 0

#define AUDIO_BANK4_REG_BIST_FAIL_ADDR                 0x5E
#define AUDIO_BANK4_REG_BIST_FAIL_GPEQ_BIST_FAIL_MASK  0xc
#define AUDIO_BANK4_REG_BIST_FAIL_GPEQ_BIST_FAIL_SHIFT 2
#define AUDIO_BANK4_REG_BIST_FAIL_ASRC_BIST_FAIL_MASK  0x2
#define AUDIO_BANK4_REG_BIST_FAIL_ASRC_BIST_FAIL_SHIFT 1
#define AUDIO_BANK4_REG_BIST_FAIL_AB_BIST_FAIL_MASK    0x1
#define AUDIO_BANK4_REG_BIST_FAIL_AB_BIST_FAIL_SHIFT   0

#define AUDIO_BANK4_REG_MUX_MMC1_MMC3_DOUT_L_ADDR                       0x60
#define AUDIO_BANK4_REG_MUX_MMC1_MMC3_DOUT_L_MUX_MMC1_MMC3_DOUT_L_MASK  0xffff
#define AUDIO_BANK4_REG_MUX_MMC1_MMC3_DOUT_L_MUX_MMC1_MMC3_DOUT_L_SHIFT 0

#define AUDIO_BANK4_REG_MUX_MMC1_MMC3_DOUT_R_ADDR                       0x62
#define AUDIO_BANK4_REG_MUX_MMC1_MMC3_DOUT_R_MUX_MMC1_MMC3_DOUT_R_MASK  0xffff
#define AUDIO_BANK4_REG_MUX_MMC1_MMC3_DOUT_R_MUX_MMC1_MMC3_DOUT_R_SHIFT 0

#define AUDIO_BANK4_REG_MMC1_DEC_OUT_L_ADDR                 0x64
#define AUDIO_BANK4_REG_MMC1_DEC_OUT_L_MMC1_DECL_DOUT_MASK  0xffff
#define AUDIO_BANK4_REG_MMC1_DEC_OUT_L_MMC1_DECL_DOUT_SHIFT 0

#define AUDIO_BANK4_REG_MMC1_DEC_OUT_R_ADDR                 0x66
#define AUDIO_BANK4_REG_MMC1_DEC_OUT_R_MMC1_DECR_DOUT_MASK  0xffff
#define AUDIO_BANK4_REG_MMC1_DEC_OUT_R_MMC1_DECR_DOUT_SHIFT 0

#define AUDIO_BANK4_REG_MMC3_DEC_OUT_L_ADDR                 0x6C
#define AUDIO_BANK4_REG_MMC3_DEC_OUT_L_MMC3_DECL_DOUT_MASK  0xffff
#define AUDIO_BANK4_REG_MMC3_DEC_OUT_L_MMC3_DECL_DOUT_SHIFT 0

#define AUDIO_BANK4_REG_MMC1_SRCOUT_L_ADDR                0x6E
#define AUDIO_BANK4_REG_MMC1_SRCOUT_L_MMC1_SRCOUT_L_MASK  0xffff
#define AUDIO_BANK4_REG_MMC1_SRCOUT_L_MMC1_SRCOUT_L_SHIFT 0

#define AUDIO_BANK4_REG_MMC1_SRCOUT_R_ADDR                0x70
#define AUDIO_BANK4_REG_MMC1_SRCOUT_R_MMC1_SRCOUT_R_MASK  0xffff
#define AUDIO_BANK4_REG_MMC1_SRCOUT_R_MMC1_SRCOUT_R_SHIFT 0

#define AUDIO_BANK4_REG_MMC3_DEC_DOUT_R_ADDR                 0x76
#define AUDIO_BANK4_REG_MMC3_DEC_DOUT_R_MMC3_DECR_DOUT_MASK  0xffff
#define AUDIO_BANK4_REG_MMC3_DEC_DOUT_R_MMC3_DECR_DOUT_SHIFT 0

#define AUDIO_BANK4_REG_SRC_MIXER1_CTL_ADDR                       0x78
#define AUDIO_BANK4_REG_SRC_MIXER1_CTL_REG_SRC_MIXER1_INV_L_MASK  0x100
#define AUDIO_BANK4_REG_SRC_MIXER1_CTL_REG_SRC_MIXER1_INV_L_SHIFT 8
#define AUDIO_BANK4_REG_SRC_MIXER1_CTL_REG_SRC_MIXER1_INV_R_MASK  0x1
#define AUDIO_BANK4_REG_SRC_MIXER1_CTL_REG_SRC_MIXER1_INV_R_SHIFT 0

#define AUDIO_BANK4_REG_DUMMY_FOR_SW_ADDR                   0x92
#define AUDIO_BANK4_REG_DUMMY_FOR_SW_REG_DUMMY_FOR_SW_MASK  0xffff
#define AUDIO_BANK4_REG_DUMMY_FOR_SW_REG_DUMMY_FOR_SW_SHIFT 0

#define AUDIO_BANK4_REG_LOG_TEST_ADDR                      0x94
#define AUDIO_BANK4_REG_LOG_TEST_REG_LOG_TEST_ENABLE_MASK  0x8000
#define AUDIO_BANK4_REG_LOG_TEST_REG_LOG_TEST_ENABLE_SHIFT 15
#define AUDIO_BANK4_REG_LOG_TEST_REG_LOG_TEST_DMA1_MASK    0x4000
#define AUDIO_BANK4_REG_LOG_TEST_REG_LOG_TEST_DMA1_SHIFT   14
#define AUDIO_BANK4_REG_LOG_TEST_REG_LOG_TEST_SELECT_MASK  0x3800
#define AUDIO_BANK4_REG_LOG_TEST_REG_LOG_TEST_SELECT_SHIFT 11

#define AUDIO_BANK4_REG_AU_SYS_STATUS0_ADDR                 0x96
#define AUDIO_BANK4_REG_AU_SYS_STATUS0_AU_SYS_STATUS0_MASK  0xffff
#define AUDIO_BANK4_REG_AU_SYS_STATUS0_AU_SYS_STATUS0_SHIFT 0

#define AUDIO_BANK4_REG_MIX1_SEL_ADDR                    0x98
#define AUDIO_BANK4_REG_MIX1_SEL_REG_DAC_DIN_L_SEL_MASK  0xc000
#define AUDIO_BANK4_REG_MIX1_SEL_REG_DAC_DIN_L_SEL_SHIFT 14
#define AUDIO_BANK4_REG_MIX1_SEL_REG_DAC_DIN_R_SEL_MASK  0x3000
#define AUDIO_BANK4_REG_MIX1_SEL_REG_DAC_DIN_R_SEL_SHIFT 12

#define AUDIO_BANK4_REG_SDM_OFFSET_ADDR                  0x9A
#define AUDIO_BANK4_REG_SDM_OFFSET_SDM_OFFSET_15_0_MASK  0xffff
#define AUDIO_BANK4_REG_SDM_OFFSET_SDM_OFFSET_15_0_SHIFT 0

#define AUDIO_BANK4_REG_SDM_CTRL_ADDR                   0x9C
#define AUDIO_BANK4_REG_SDM_CTRL_SDM_OFFSET_17_16_MASK  0xc000
#define AUDIO_BANK4_REG_SDM_CTRL_SDM_OFFSET_17_16_SHIFT 14
#define AUDIO_BANK4_REG_SDM_CTRL_REG_SDM_TEST_EN_MASK   0x1000
#define AUDIO_BANK4_REG_SDM_CTRL_REG_SDM_TEST_EN_SHIFT  12
#define AUDIO_BANK4_REG_SDM_CTRL_REG_SDM_SFT_DIS_MASK   0x800
#define AUDIO_BANK4_REG_SDM_CTRL_REG_SDM_SFT_DIS_SHIFT  11
#define AUDIO_BANK4_REG_SDM_CTRL_REG_DAC_TEST_EN_MASK   0x400
#define AUDIO_BANK4_REG_SDM_CTRL_REG_DAC_TEST_EN_SHIFT  10
#define AUDIO_BANK4_REG_SDM_CTRL_REG_FIX_MSB_EN_MASK    0x200
#define AUDIO_BANK4_REG_SDM_CTRL_REG_FIX_MSB_EN_SHIFT   9
#define AUDIO_BANK4_REG_SDM_CTRL_REG_FIX_MSB_SEL_MASK   0x1f0
#define AUDIO_BANK4_REG_SDM_CTRL_REG_FIX_MSB_SEL_SHIFT  4
#define AUDIO_BANK4_REG_SDM_CTRL_REG_DITHER_EN_MASK     0x8
#define AUDIO_BANK4_REG_SDM_CTRL_REG_DITHER_EN_SHIFT    3
#define AUDIO_BANK4_REG_SDM_CTRL_REG_DITHER_SEL_MASK    0x7
#define AUDIO_BANK4_REG_SDM_CTRL_REG_DITHER_SEL_SHIFT   0

#define AUDIO_BANK4_REG_SDM_CTRL0_ADDR                    0xA2
#define AUDIO_BANK4_REG_SDM_CTRL0_REG_BOUNDARY1_SEL_MASK  0xff00
#define AUDIO_BANK4_REG_SDM_CTRL0_REG_BOUNDARY1_SEL_SHIFT 8
#define AUDIO_BANK4_REG_SDM_CTRL0_REG_BOUNDARY0_SEL_MASK  0xff
#define AUDIO_BANK4_REG_SDM_CTRL0_REG_BOUNDARY0_SEL_SHIFT 0

#define AUDIO_BANK4_REG_SDM_CTRL1_ADDR                    0xA4
#define AUDIO_BANK4_REG_SDM_CTRL1_REG_BOUNDARY3_SEL_MASK  0xff00
#define AUDIO_BANK4_REG_SDM_CTRL1_REG_BOUNDARY3_SEL_SHIFT 8
#define AUDIO_BANK4_REG_SDM_CTRL1_REG_BOUNDARY2_SEL_MASK  0xff
#define AUDIO_BANK4_REG_SDM_CTRL1_REG_BOUNDARY2_SEL_SHIFT 0

#define AUDIO_BANK4_REG_SDM_CTRL2_ADDR                     0xA6
#define AUDIO_BANK4_REG_SDM_CTRL2_REG_CODEC_Q2_LEVEL_MASK  0x3f00
#define AUDIO_BANK4_REG_SDM_CTRL2_REG_CODEC_Q2_LEVEL_SHIFT 8
#define AUDIO_BANK4_REG_SDM_CTRL2_REG_CODEC_Q1_LEVEL_MASK  0x3f
#define AUDIO_BANK4_REG_SDM_CTRL2_REG_CODEC_Q1_LEVEL_SHIFT 0

#define AUDIO_BANK4_REG_SDM_CTRL3_ADDR                     0xA8
#define AUDIO_BANK4_REG_SDM_CTRL3_REG_CODEC_Q4_LEVEL_MASK  0x3f00
#define AUDIO_BANK4_REG_SDM_CTRL3_REG_CODEC_Q4_LEVEL_SHIFT 8
#define AUDIO_BANK4_REG_SDM_CTRL3_REG_CODEC_Q3_LEVEL_MASK  0x3f
#define AUDIO_BANK4_REG_SDM_CTRL3_REG_CODEC_Q3_LEVEL_SHIFT 0

#define AUDIO_BANK4_REG_SDM_CTRL4_ADDR                     0xAA
#define AUDIO_BANK4_REG_SDM_CTRL4_REG_FIRST_ORDER_EN_MASK  0x2
#define AUDIO_BANK4_REG_SDM_CTRL4_REG_FIRST_ORDER_EN_SHIFT 1
#define AUDIO_BANK4_REG_SDM_CTRL4_REG_SDM_EN_MASK          0x1
#define AUDIO_BANK4_REG_SDM_CTRL4_REG_SDM_EN_SHIFT         0

#define AUDIO_BANK4_REG_AU_SYS_CTRL0_ADDR                    0xAC
#define AUDIO_BANK4_REG_AU_SYS_CTRL0_REG_SDM_FIFO_EX_MASK    0x40
#define AUDIO_BANK4_REG_AU_SYS_CTRL0_REG_SDM_FIFO_EX_SHIFT   6
#define AUDIO_BANK4_REG_AU_SYS_CTRL0_REG_SDM_FIFO_CLR_MASK   0x20
#define AUDIO_BANK4_REG_AU_SYS_CTRL0_REG_SDM_FIFO_CLR_SHIFT  5
#define AUDIO_BANK4_REG_AU_SYS_CTRL0_REG_ADC_FIFO_EX_MASK    0x10
#define AUDIO_BANK4_REG_AU_SYS_CTRL0_REG_ADC_FIFO_EX_SHIFT   4
#define AUDIO_BANK4_REG_AU_SYS_CTRL0_REG_ADC_FIFO_CLR_MASK   0x8
#define AUDIO_BANK4_REG_AU_SYS_CTRL0_REG_ADC_FIFO_CLR_SHIFT  3
#define AUDIO_BANK4_REG_AU_SYS_CTRL0_REG_EN_ADC_DITHER_MASK  0x1
#define AUDIO_BANK4_REG_AU_SYS_CTRL0_REG_EN_ADC_DITHER_SHIFT 0

#define AUDIO_BANK4_REG_SDM_DIN_CFG_00_ADDR                         0xAE
#define AUDIO_BANK4_REG_SDM_DIN_CFG_00_REG_SDM_DIN_L_SEL_MASK       0xe000
#define AUDIO_BANK4_REG_SDM_DIN_CFG_00_REG_SDM_DIN_L_SEL_SHIFT      13
#define AUDIO_BANK4_REG_SDM_DIN_CFG_00_REG_SDM_DIN_L_STEP_CNT_MASK  0x1fff
#define AUDIO_BANK4_REG_SDM_DIN_CFG_00_REG_SDM_DIN_L_STEP_CNT_SHIFT 0

#define AUDIO_BANK4_REG_SDM_DIN_CFG_01_ADDR                         0xB0
#define AUDIO_BANK4_REG_SDM_DIN_CFG_01_REG_SDM_DIN_R_SEL_MASK       0xe000
#define AUDIO_BANK4_REG_SDM_DIN_CFG_01_REG_SDM_DIN_R_SEL_SHIFT      13
#define AUDIO_BANK4_REG_SDM_DIN_CFG_01_REG_SDM_DIN_R_STEP_CNT_MASK  0x1fff
#define AUDIO_BANK4_REG_SDM_DIN_CFG_01_REG_SDM_DIN_R_STEP_CNT_SHIFT 0

#define AUDIO_BANK4_REG_FIXVALUE_CTRL0_ADDR                    0xB2
#define AUDIO_BANK4_REG_FIXVALUE_CTRL0_REG_FIXVALUE_HIGH_MASK  0x3ff
#define AUDIO_BANK4_REG_FIXVALUE_CTRL0_REG_FIXVALUE_HIGH_SHIFT 0

#define AUDIO_BANK4_REG_FIXVALUE_CTRL1_ADDR                   0xB4
#define AUDIO_BANK4_REG_FIXVALUE_CTRL1_REG_FIXVALUE_LOW_MASK  0xff
#define AUDIO_BANK4_REG_FIXVALUE_CTRL1_REG_FIXVALUE_LOW_SHIFT 0

#define AUDIO_BANK4_REG_FIXVALUE_CTRL2_ADDR              0xB6
#define AUDIO_BANK4_REG_FIXVALUE_CTRL2_REG_DWA_FIX_MASK  0x2
#define AUDIO_BANK4_REG_FIXVALUE_CTRL2_REG_DWA_FIX_SHIFT 1
#define AUDIO_BANK4_REG_FIXVALUE_CTRL2_REG_SDM_FIX_MASK  0x1
#define AUDIO_BANK4_REG_FIXVALUE_CTRL2_REG_SDM_FIX_SHIFT 0

#define AUDIO_BANK4_REG_SDM_MIXER_DOUT_L_ADDR                   0xB8
#define AUDIO_BANK4_REG_SDM_MIXER_DOUT_L_SDM_MIXER_DOUT_L_MASK  0xffff
#define AUDIO_BANK4_REG_SDM_MIXER_DOUT_L_SDM_MIXER_DOUT_L_SHIFT 0

#define AUDIO_BANK4_REG_SDM_MIXER_DOUT_R_ADDR                   0xBA
#define AUDIO_BANK4_REG_SDM_MIXER_DOUT_R_SDM_MIXER_DOUT_R_MASK  0xffff
#define AUDIO_BANK4_REG_SDM_MIXER_DOUT_R_SDM_MIXER_DOUT_R_SHIFT 0

#define AUDIO_BANK4_REG_GSM_UL_COEF0_ADDR                  0xD0
#define AUDIO_BANK4_REG_GSM_UL_COEF0_REG_FIR1_COEF_0_MASK  0xffff
#define AUDIO_BANK4_REG_GSM_UL_COEF0_REG_FIR1_COEF_0_SHIFT 0

#define AUDIO_BANK4_REG_GSM_UL_COEF1_ADDR                  0xD2
#define AUDIO_BANK4_REG_GSM_UL_COEF1_REG_FIR1_COEF_1_MASK  0xffff
#define AUDIO_BANK4_REG_GSM_UL_COEF1_REG_FIR1_COEF_1_SHIFT 0

#define AUDIO_BANK4_REG_GSM_UL_COEF2_ADDR                  0xD4
#define AUDIO_BANK4_REG_GSM_UL_COEF2_REG_FIR1_COEF_2_MASK  0xffff
#define AUDIO_BANK4_REG_GSM_UL_COEF2_REG_FIR1_COEF_2_SHIFT 0

#define AUDIO_BANK4_REG_GSM_UL_COEF3_ADDR                  0xD6
#define AUDIO_BANK4_REG_GSM_UL_COEF3_REG_FIR1_COEF_3_MASK  0xffff
#define AUDIO_BANK4_REG_GSM_UL_COEF3_REG_FIR1_COEF_3_SHIFT 0

#define AUDIO_BANK4_REG_GSM_UL_COEF4_ADDR                  0xD8
#define AUDIO_BANK4_REG_GSM_UL_COEF4_REG_FIR1_COEF_4_MASK  0xffff
#define AUDIO_BANK4_REG_GSM_UL_COEF4_REG_FIR1_COEF_4_SHIFT 0

#define AUDIO_BANK4_REG_ADC_CTRL0_ADDR                   0xDA
#define AUDIO_BANK4_REG_ADC_CTRL0_REG_ADC_CIC_GAIN_MASK  0xff
#define AUDIO_BANK4_REG_ADC_CTRL0_REG_ADC_CIC_GAIN_SHIFT 0

#define AUDIO_BANK4_REG_EXT_I2S_TEST_MD_ADDR                         0xDC
#define AUDIO_BANK4_REG_EXT_I2S_TEST_MD_REG_SINE_GEN_ENA_ADC_L_MASK  0x8000
#define AUDIO_BANK4_REG_EXT_I2S_TEST_MD_REG_SINE_GEN_ENA_ADC_L_SHIFT 15
#define AUDIO_BANK4_REG_EXT_I2S_TEST_MD_REG_SINE_GEN_ENA_ADC_R_MASK  0x4000
#define AUDIO_BANK4_REG_EXT_I2S_TEST_MD_REG_SINE_GEN_ENA_ADC_R_SHIFT 14
#define AUDIO_BANK4_REG_EXT_I2S_TEST_MD_REG_SINE_GEN_GAIN_ADC_MASK   0xf0
#define AUDIO_BANK4_REG_EXT_I2S_TEST_MD_REG_SINE_GEN_GAIN_ADC_SHIFT  4
#define AUDIO_BANK4_REG_EXT_I2S_TEST_MD_REG_SINE_GEN_FREQ_ADC_MASK   0xf
#define AUDIO_BANK4_REG_EXT_I2S_TEST_MD_REG_SINE_GEN_FREQ_ADC_SHIFT  0

#define AUDIO_BANK4_REG_ADC_OUT_SEL_ADDR                    0xE0
#define AUDIO_BANK4_REG_ADC_OUT_SEL_REG_ADC_OUT_2_SEL_MASK  0xc
#define AUDIO_BANK4_REG_ADC_OUT_SEL_REG_ADC_OUT_2_SEL_SHIFT 2
#define AUDIO_BANK4_REG_ADC_OUT_SEL_REG_ADC_OUT_1_SEL_MASK  0x3
#define AUDIO_BANK4_REG_ADC_OUT_SEL_REG_ADC_OUT_1_SEL_SHIFT 0

#define AUDIO_BANK4_REG_BYTE_WR_EN_MODE_ADDR                  0xE2
#define AUDIO_BANK4_REG_BYTE_WR_EN_MODE_BYTE_WR_EN_MODE_MASK  0x8000
#define AUDIO_BANK4_REG_BYTE_WR_EN_MODE_BYTE_WR_EN_MODE_SHIFT 15

#define AUDIO_BANK4_REG_BYTE_AUDIO_CLK_GATE_FORCE_ON                    0xE4
#define AUDIO_BANK4_REG_BYTE_AUDIO_VREC_PCM_CLK_GATE_FORCE_ON_MASK      0x400
#define AUDIO_BANK4_REG_BYTE_AUDIO_VREC_PCM_CLK_GATE_FORCE_ON_SHIFT     10
#define AUDIO_BANK4_REG_BYTE_AUDIO_VREC_MEN_CNT_CLK_GATE_FORCE_ON_MASK  0x200
#define AUDIO_BANK4_REG_BYTE_AUDIO_VREC_MEN_CNT_CLK_GATE_FORCE_ON_SHIFT 9
#define AUDIO_BANK4_REG_BYTE_AUDIO_VREC_MAC_ROM_CLK_GATE_FORCE_ON_MASK  0x100
#define AUDIO_BANK4_REG_BYTE_AUDIO_VREC_MAC_ROM_CLK_GATE_FORCE_ON_SHIFT 8
#define AUDIO_BANK4_REG_BYTE_AUDIO_SDM_CLK_GATE_FORCE_ON_MASK           0x80
#define AUDIO_BANK4_REG_BYTE_AUDIO_SDM_CLK_GATE_FORCE_ON_SHIFT          7
#define AUDIO_BANK4_REG_BYTE_AUDIO_MEM_CNT_CLK_GATE_FORCE_ON_MASK       0x40
#define AUDIO_BANK4_REG_BYTE_AUDIO_MEM_CNT_CLK_GATE_FORCE_ON_SHIFT      6
#define AUDIO_BANK4_REG_BYTE_AUDIO_MAC_ROM_CLK_GATE_FORCE_ON_MASK       0x20
#define AUDIO_BANK4_REG_BYTE_AUDIO_MAC_ROM_CLK_GATE_FORCE_ON_SHIFT      5
#define AUDIO_BANK4_REG_BYTE_AUDIO_SCALMECH_CLK_GATE_FORCE_ON_MASK      0x10
#define AUDIO_BANK4_REG_BYTE_AUDIO_SCALMECH_CLK_GATE_FORCE_ON_SHIFT     4
#define AUDIO_BANK4_REG_BYTE_AUDIO_DEC_CIC2_CLK_GATE_FORCE_ON_MASK      0x8
#define AUDIO_BANK4_REG_BYTE_AUDIO_DEC_CIC2_CLK_GATE_FORCE_ON_SHIFT     3
#define AUDIO_BANK4_REG_BYTE_AUDIO_DEC_CIC1_CLK_GATE_FORCE_ON_MASK      0x4
#define AUDIO_BANK4_REG_BYTE_AUDIO_DEC_CIC1_CLK_GATE_FORCE_ON_SHIFT     2
#define AUDIO_BANK4_REG_BYTE_AUDIO_LINEAR_INT_CLK_GATE_FORCE_ON_MASK    0x2
#define AUDIO_BANK4_REG_BYTE_AUDIO_LINEAR_INT_CLK_GATE_FORCE_ON_SHIFT   1
#define AUDIO_BANK4_REG_BYTE_AUDIO_ADC_CIC_CLK_GATE_FORCE_ON_MASK       0x1
#define AUDIO_BANK4_REG_BYTE_AUDIO_ADC_CIC_CLK_GATE_FORCE_ON_SHIFT      0

#endif
