/*
 * audio_bank3_sw_reg_define.h - Sigmastar
 *
 * Copyright (c) [2019~2022] SigmaStar Technology.
 *
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details.
 *
 */

#ifndef __JM_AUDIO_BANK3_SW_REG_DEFINE_H__
#define __JM_AUDIO_BANK3_SW_REG_DEFINE_H__

#define AUDIO_BANK3_REG_VREC_CTRL00_ADDR                    0x00
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_AB_VREC_MASK  0x4000
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_AB_VREC_SHIFT 14
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_TG_MASK       0x2000
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_TG_SHIFT      13
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_DMA_MASK      0x1000
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_DMA_SHIFT     12
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_CIC_MASK      0x200
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_CIC_SHIFT     9
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_DMIC_MASK     0x100
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_DMIC_SHIFT    8
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_VREC_MASK     0x1
#define AUDIO_BANK3_REG_VREC_CTRL00_REG_RESET_VREC_SHIFT    0

#define AUDIO_BANK3_REG_VREC_CTRL01_ADDR                      0x02
#define AUDIO_BANK3_REG_VREC_CTRL01_REG_DIG_MIC_CH_MASK       0x70
#define AUDIO_BANK3_REG_VREC_CTRL01_REG_DIG_MIC_CH_SHIFT      4
#define AUDIO_BANK3_REG_VREC_CTRL01_REG_DMA_PAUSE_MASK        0x4
#define AUDIO_BANK3_REG_VREC_CTRL01_REG_DMA_PAUSE_SHIFT       2
#define AUDIO_BANK3_REG_VREC_CTRL01_REG_DIG_MIC_BCK_INV_MASK  0x2
#define AUDIO_BANK3_REG_VREC_CTRL01_REG_DIG_MIC_BCK_INV_SHIFT 1
#define AUDIO_BANK3_REG_VREC_CTRL01_REG_DIG_MIC_EN_MASK       0x1
#define AUDIO_BANK3_REG_VREC_CTRL01_REG_DIG_MIC_EN_SHIFT      0

#define AUDIO_BANK3_REG_VREC_CTRL02_ADDR                      0x04
#define AUDIO_BANK3_REG_VREC_CTRL02_REG_SEL_I2S_RX_VREC_MASK  0x2
#define AUDIO_BANK3_REG_VREC_CTRL02_REG_SEL_I2S_RX_VREC_SHIFT 1

#define AUDIO_BANK3_REG_VREC_CTRL03_ADDR                  0x06
#define AUDIO_BANK3_REG_VREC_CTRL03_SIN_FREQ_SEL_MASK     0xf000
#define AUDIO_BANK3_REG_VREC_CTRL03_SIN_FREQ_SEL_SHIFT    12
#define AUDIO_BANK3_REG_VREC_CTRL03_SIN_GAIN_MASK         0xf00
#define AUDIO_BANK3_REG_VREC_CTRL03_SIN_GAIN_SHIFT        8
#define AUDIO_BANK3_REG_VREC_CTRL03_SIN_PATH_SEL_MASK     0x40
#define AUDIO_BANK3_REG_VREC_CTRL03_SIN_PATH_SEL_SHIFT    6
#define AUDIO_BANK3_REG_VREC_CTRL03_SIN_PATH_SEL_LR_MASK  0x30
#define AUDIO_BANK3_REG_VREC_CTRL03_SIN_PATH_SEL_LR_SHIFT 4
#define AUDIO_BANK3_REG_VREC_CTRL03_SIN_EN_MASK           0xf
#define AUDIO_BANK3_REG_VREC_CTRL03_SIN_EN_SHIFT          0

#define AUDIO_BANK3_REG_VREC_CTRL04_ADDR               0x08
#define AUDIO_BANK3_REG_VREC_CTRL04_REG_MODE_ALL_MASK  0x1f
#define AUDIO_BANK3_REG_VREC_CTRL04_REG_MODE_ALL_SHIFT 0

#define AUDIO_BANK3_REG_VREC_CTRL05_ADDR                0x0A
#define AUDIO_BANK3_REG_VREC_CTRL05_REG_MODE_AUTO_MASK  0x8000
#define AUDIO_BANK3_REG_VREC_CTRL05_REG_MODE_AUTO_SHIFT 15
#define AUDIO_BANK3_REG_VREC_CTRL05_REG_MODE_FS_MASK    0x300
#define AUDIO_BANK3_REG_VREC_CTRL05_REG_MODE_FS_SHIFT   8
#define AUDIO_BANK3_REG_VREC_CTRL05_REG_MODE_CIC_MASK   0xf0
#define AUDIO_BANK3_REG_VREC_CTRL05_REG_MODE_CIC_SHIFT  4
#define AUDIO_BANK3_REG_VREC_CTRL05_REG_MODE_BCK_MASK   0xf
#define AUDIO_BANK3_REG_VREC_CTRL05_REG_MODE_BCK_SHIFT  0

#define AUDIO_BANK3_REG_VREC_CTRL06_ADDR                        0x0C
#define AUDIO_BANK3_REG_VREC_CTRL06_REG_INIT_SRAM_EN_VREC_MASK  0x8000
#define AUDIO_BANK3_REG_VREC_CTRL06_REG_INIT_SRAM_EN_VREC_SHIFT 15
#define AUDIO_BANK3_REG_VREC_CTRL06_REG_TG_BCK_FFOUT_MASK       0x200
#define AUDIO_BANK3_REG_VREC_CTRL06_REG_TG_BCK_FFOUT_SHIFT      9
#define AUDIO_BANK3_REG_VREC_CTRL06_REG_TG_EN_MASK              0x100
#define AUDIO_BANK3_REG_VREC_CTRL06_REG_TG_EN_SHIFT             8
#define AUDIO_BANK3_REG_VREC_CTRL06_REG_TIME_GEN_EN_VREC_MASK   0x10
#define AUDIO_BANK3_REG_VREC_CTRL06_REG_TIME_GEN_EN_VREC_SHIFT  4
#define AUDIO_BANK3_REG_VREC_CTRL06_REG_EN_DEC_1_VREC_MASK      0x1
#define AUDIO_BANK3_REG_VREC_CTRL06_REG_EN_DEC_1_VREC_SHIFT     0

#define AUDIO_BANK3_REG_VREC_CTRL07_ADDR                                   0x0E
#define AUDIO_BANK3_REG_VREC_CTRL07_REG_DMIC_EXT_CLK_DEGLITCH_NUM_MASK     0x70
#define AUDIO_BANK3_REG_VREC_CTRL07_REG_DMIC_EXT_CLK_DEGLITCH_NUM_SHIFT    4
#define AUDIO_BANK3_REG_VREC_CTRL07_REG_DMIC_EXT_CLK_DEGLITCH_ENABLE_MASK  0x8
#define AUDIO_BANK3_REG_VREC_CTRL07_REG_DMIC_EXT_CLK_DEGLITCH_ENABLE_SHIFT 3
#define AUDIO_BANK3_REG_VREC_CTRL07_REG_DIG_MIC_CLK_SEL_MASK               0x1
#define AUDIO_BANK3_REG_VREC_CTRL07_REG_DIG_MIC_CLK_SEL_SHIFT              0

#define AUDIO_BANK3_REG_DMIC_CTRL0_ADDR                     0x20
#define AUDIO_BANK3_REG_DMIC_CTRL0_REG_DIG_MIC_PD_CH1_MASK  0x10
#define AUDIO_BANK3_REG_DMIC_CTRL0_REG_DIG_MIC_PD_CH1_SHIFT 4

#define AUDIO_BANK3_REG_DMIC_CTRL1_ADDR                                  0x22
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DIG_MIC_IN_VLD_SYNC_CNT_CH1_MASK  0x3f00
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DIG_MIC_IN_VLD_SYNC_CNT_CH1_SHIFT 8
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DBG_CFG_CH1_MASK                  0xf0
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DBG_CFG_CH1_SHIFT                 4
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DIG_MIC_IN_R_INV_CH1_MASK         0x8
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DIG_MIC_IN_R_INV_CH1_SHIFT        3
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DIG_MIC_IN_L_INV_CH1_MASK         0x4
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DIG_MIC_IN_L_INV_CH1_SHIFT        2
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DIG_MIC_IN_DG_EN_CH1_MASK         0x2
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DIG_MIC_IN_DG_EN_CH1_SHIFT        1
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DIG_MIC_IN_LR_SYNC_EN_CH1_MASK    0x1
#define AUDIO_BANK3_REG_DMIC_CTRL1_REG_DIG_MIC_IN_LR_SYNC_EN_CH1_SHIFT   0

#define AUDIO_BANK3_REG_DMIC_CTRL2_ADDR                                  0x24
#define AUDIO_BANK3_REG_DMIC_CTRL2_REG_AUTO_CNT_CH1_MASK                 0x8000
#define AUDIO_BANK3_REG_DMIC_CTRL2_REG_AUTO_CNT_CH1_SHIFT                15
#define AUDIO_BANK3_REG_DMIC_CTRL2_REG_DIG_MIC_IN_R_SAMPLE_CNT_CH1_MASK  0x3f00
#define AUDIO_BANK3_REG_DMIC_CTRL2_REG_DIG_MIC_IN_R_SAMPLE_CNT_CH1_SHIFT 8
#define AUDIO_BANK3_REG_DMIC_CTRL2_REG_DIG_MIC_IN_L_SAMPLE_CNT_CH1_MASK  0x3f
#define AUDIO_BANK3_REG_DMIC_CTRL2_REG_DIG_MIC_IN_L_SAMPLE_CNT_CH1_SHIFT 0

#define AUDIO_BANK3_REG_CIC_CTRL0_ADDR                0x40
#define AUDIO_BANK3_REG_CIC_CTRL0_REG_CIC_PD_1R_MASK  0x20
#define AUDIO_BANK3_REG_CIC_CTRL0_REG_CIC_PD_1R_SHIFT 5
#define AUDIO_BANK3_REG_CIC_CTRL0_REG_CIC_PD_1L_MASK  0x10
#define AUDIO_BANK3_REG_CIC_CTRL0_REG_CIC_PD_1L_SHIFT 4
#define AUDIO_BANK3_REG_CIC_CTRL0_REG_CIC_EN_MASK     0x1
#define AUDIO_BANK3_REG_CIC_CTRL0_REG_CIC_EN_SHIFT    0

#define AUDIO_BANK3_REG_CIC_CTRL1_ADDR                          0x42
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_GAIN_1R_MASK          0x7000
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_GAIN_1R_SHIFT         12
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_GAIN_1L_MASK          0x700
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_GAIN_1L_SHIFT         8
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_CFG_1R_MASK           0xc0
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_CFG_1R_SHIFT          6
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_CFG_1L_MASK           0x30
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_CFG_1L_SHIFT          4
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_GAIN_BYPASS_1LR_MASK  0x4
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_GAIN_BYPASS_1LR_SHIFT 2
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_THREE_STAGE_1LR_MASK  0x1
#define AUDIO_BANK3_REG_CIC_CTRL1_REG_CIC_THREE_STAGE_1LR_SHIFT 0

#define AUDIO_BANK3_REG_CIC_COMPENSATE_GAIN_0_ADDR                              0x50
#define AUDIO_BANK3_REG_CIC_COMPENSATE_GAIN_0_REG_CIC_COMPENSATE_GAIN_CH2_MASK  0xff00
#define AUDIO_BANK3_REG_CIC_COMPENSATE_GAIN_0_REG_CIC_COMPENSATE_GAIN_CH2_SHIFT 8
#define AUDIO_BANK3_REG_CIC_COMPENSATE_GAIN_0_REG_CIC_COMPENSATE_GAIN_CH1_MASK  0xff
#define AUDIO_BANK3_REG_CIC_COMPENSATE_GAIN_0_REG_CIC_COMPENSATE_GAIN_CH1_SHIFT 0

#define AUDIO_BANK3_REG_DIG_MIC_CTRL0_ADDR                   0x58
#define AUDIO_BANK3_REG_DIG_MIC_CTRL0_REG_VREC_CH1_SEL_MASK  0x40
#define AUDIO_BANK3_REG_DIG_MIC_CTRL0_REG_VREC_CH1_SEL_SHIFT 6
#define AUDIO_BANK3_REG_DIG_MIC_CTRL0_REG_VREC_CH2_SEL_MASK  0x20
#define AUDIO_BANK3_REG_DIG_MIC_CTRL0_REG_VREC_CH2_SEL_SHIFT 5
#define AUDIO_BANK3_REG_DIG_MIC_CTRL0_REG_VREC_BCK_SEL_MASK  0x10
#define AUDIO_BANK3_REG_DIG_MIC_CTRL0_REG_VREC_BCK_SEL_SHIFT 4

#define AUDIO_BANK3_REG_VREC_HPF_CFG_00_ADDR                   0x5A
#define AUDIO_BANK3_REG_VREC_HPF_CFG_00_REG_VREC_SAT_SEL_MASK  0x40
#define AUDIO_BANK3_REG_VREC_HPF_CFG_00_REG_VREC_SAT_SEL_SHIFT 6
#define AUDIO_BANK3_REG_VREC_HPF_CFG_00_REG_BP_VREC_HPF2_MASK  0x20
#define AUDIO_BANK3_REG_VREC_HPF_CFG_00_REG_BP_VREC_HPF2_SHIFT 5
#define AUDIO_BANK3_REG_VREC_HPF_CFG_00_REG_BP_VREC_HPF1_MASK  0x10
#define AUDIO_BANK3_REG_VREC_HPF_CFG_00_REG_BP_VREC_HPF1_SHIFT 4
#define AUDIO_BANK3_REG_VREC_HPF_CFG_00_REG_VREC_HPF_N_MASK    0xf
#define AUDIO_BANK3_REG_VREC_HPF_CFG_00_REG_VREC_HPF_N_SHIFT   0

#define AUDIO_BANK3_REG_VREC_CTRL08_ADDR                       0x78
#define AUDIO_BANK3_REG_VREC_CTRL08_REG_EN_CLK_GATE_CH1_MASK   0x4
#define AUDIO_BANK3_REG_VREC_CTRL08_REG_EN_CLK_GATE_CH1_SHIFT  2
#define AUDIO_BANK3_REG_VREC_CTRL08_REG_EN_CLK_GATE_CH0_MASK   0x2
#define AUDIO_BANK3_REG_VREC_CTRL08_REG_EN_CLK_GATE_CH0_SHIFT  1
#define AUDIO_BANK3_REG_VREC_CTRL08_REG_EN_CLK_GATE_AUTO_MASK  0x1
#define AUDIO_BANK3_REG_VREC_CTRL08_REG_EN_CLK_GATE_AUTO_SHIFT 0

#define AUDIO_BANK3_REG_VREC_STATUS00_ADDR                 0xE0
#define AUDIO_BANK3_REG_VREC_STATUS00_DBG_5FS_MASK         0x40
#define AUDIO_BANK3_REG_VREC_STATUS00_DBG_5FS_SHIFT        6
#define AUDIO_BANK3_REG_VREC_STATUS00_DBG_FS_MASK          0x20
#define AUDIO_BANK3_REG_VREC_STATUS00_DBG_FS_SHIFT         5
#define AUDIO_BANK3_REG_VREC_STATUS00_DIG_MIC_BCK_MASK     0x10
#define AUDIO_BANK3_REG_VREC_STATUS00_DIG_MIC_BCK_SHIFT    4
#define AUDIO_BANK3_REG_VREC_STATUS00_DIG_MIC_IN_CH2_MASK  0x2
#define AUDIO_BANK3_REG_VREC_STATUS00_DIG_MIC_IN_CH2_SHIFT 1
#define AUDIO_BANK3_REG_VREC_STATUS00_DIG_MIC_IN_CH1_MASK  0x1
#define AUDIO_BANK3_REG_VREC_STATUS00_DIG_MIC_IN_CH1_SHIFT 0

#define AUDIO_BANK3_REG_VREC_STATUS01_ADDR                   0xE2
#define AUDIO_BANK3_REG_VREC_STATUS01_REG_DBG_TBUS_CH1_MASK  0xff
#define AUDIO_BANK3_REG_VREC_STATUS01_REG_DBG_TBUS_CH1_SHIFT 0

#define AUDIO_BANK3_REG_VREC_STATUS02_ADDR                  0xE4
#define AUDIO_BANK3_REG_VREC_STATUS02_REG_CIC_TBUS_1R_MASK  0xc
#define AUDIO_BANK3_REG_VREC_STATUS02_REG_CIC_TBUS_1R_SHIFT 2
#define AUDIO_BANK3_REG_VREC_STATUS02_REG_CIC_TBUS_1L_MASK  0x3
#define AUDIO_BANK3_REG_VREC_STATUS02_REG_CIC_TBUS_1L_SHIFT 0

#define AUDIO_BANK3_REG_VREC_STATUS03_ADDR               0xE6
#define AUDIO_BANK3_REG_VREC_STATUS03_CH1_CICOUT_L_MASK  0xff00
#define AUDIO_BANK3_REG_VREC_STATUS03_CH1_CICOUT_L_SHIFT 8
#define AUDIO_BANK3_REG_VREC_STATUS03_CH1_CICOUT_R_MASK  0xff
#define AUDIO_BANK3_REG_VREC_STATUS03_CH1_CICOUT_R_SHIFT 0

#define AUDIO_BANK3_REG_VREC_STATUS07_ADDR                0xEE
#define AUDIO_BANK3_REG_VREC_STATUS07_VREC_ADC_HB0L_MASK  0xff00
#define AUDIO_BANK3_REG_VREC_STATUS07_VREC_ADC_HB0L_SHIFT 8
#define AUDIO_BANK3_REG_VREC_STATUS07_VREC_ADC_HB0R_MASK  0xff
#define AUDIO_BANK3_REG_VREC_STATUS07_VREC_ADC_HB0R_SHIFT 0

#endif
