/*
 * audio_bank2_sw_reg_define.h - Sigmastar
 *
 * Copyright (c) [2019~2022] SigmaStar Technology.
 *
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details.
 *
 */

#ifndef __JM_AUDIO_BANK2_SW_REG_DEFINE_H__
#define __JM_AUDIO_BANK2_SW_REG_DEFINE_H__

#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG1_ADDR                                 0x02
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG1_REG_I2S_TDM_REG_GAIN_L_MASK          0x3ff0
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG1_REG_I2S_TDM_REG_GAIN_L_SHIFT         4
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG1_REG_I2S_TDM_TX_DPGA_STATUS_CLR_MASK  0x8
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG1_REG_I2S_TDM_TX_DPGA_STATUS_CLR_SHIFT 3
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG1_REG_I2S_TDM_MUTE_2_ZERO_MASK         0x4
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG1_REG_I2S_TDM_MUTE_2_ZERO_SHIFT        2
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG1_REG_I2S_TDM_FADING_EN_MASK           0x2
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG1_REG_I2S_TDM_FADING_EN_SHIFT          1
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG1_REG_I2S_TDM_DPGA_EN_MASK             0x1
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG1_REG_I2S_TDM_DPGA_EN_SHIFT            0

#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG2_ADDR                         0x04
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG2_REG_I2S_TDM_REG_GAIN_R_MASK  0x3ff0
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG2_REG_I2S_TDM_REG_GAIN_R_SHIFT 4
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG2_REG_I2S_TDM_STEP_MASK        0x7
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG2_REG_I2S_TDM_STEP_SHIFT       0

#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG3_ADDR                           0x06
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG3_REG_I2S_TDM_REG_OFFSET_R_MASK  0x7f00
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG3_REG_I2S_TDM_REG_OFFSET_R_SHIFT 8
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG3_REG_I2S_TDM_REG_OFFSET_L_MASK  0x7f
#define AUDIO_BANK2_REG_I2S_TDM_DPGA_CFG3_REG_I2S_TDM_REG_OFFSET_L_SHIFT 0

#define AUDIO_BANK2_REG_I2S_TDM_STS_00_ADDR                           0x08
#define AUDIO_BANK2_REG_I2S_TDM_STS_00_I2S_TDM_MUTE_DONE_L_MASK       0x2000
#define AUDIO_BANK2_REG_I2S_TDM_STS_00_I2S_TDM_MUTE_DONE_L_SHIFT      13
#define AUDIO_BANK2_REG_I2S_TDM_STS_00_I2S_TDM_MUTE_DONE_R_MASK       0x1000
#define AUDIO_BANK2_REG_I2S_TDM_STS_00_I2S_TDM_MUTE_DONE_R_SHIFT      12
#define AUDIO_BANK2_REG_I2S_TDM_STS_00_I2S_TDM_TX_DPGA_STATUS_MASK    0xe00
#define AUDIO_BANK2_REG_I2S_TDM_STS_00_I2S_TDM_TX_DPGA_STATUS_SHIFT   9
#define AUDIO_BANK2_REG_I2S_TDM_STS_00_I2S_TDM_RX_FIFO_STATUS_MASK    0x100
#define AUDIO_BANK2_REG_I2S_TDM_STS_00_I2S_TDM_RX_FIFO_STATUS_SHIFT   8
#define AUDIO_BANK2_REG_I2S_TDM_STS_00_I2S_TX_FIFO_STATUS_CODEC_MASK  0xff
#define AUDIO_BANK2_REG_I2S_TDM_STS_00_I2S_TX_FIFO_STATUS_CODEC_SHIFT 0

#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_ADDR                              0x0A
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_MS_MODE_MASK     0x4000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_MS_MODE_SHIFT    14
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_TDM_CHLEN_MASK      0x1c00
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_TDM_CHLEN_SHIFT     10
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_ENC_WDTH_MASK    0x200
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_ENC_WDTH_SHIFT   9
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_WS_FMT_MASK      0x80
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_WS_FMT_SHIFT     7
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_FMT_MASK         0x40
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_FMT_SHIFT        6
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_WS_INV_MASK      0x20
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_WS_INV_SHIFT     5
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_BCK_DG_EN_MASK   0x8
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_BCK_DG_EN_SHIFT  3
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_BCK_DG_NUM_MASK  0x7
#define AUDIO_BANK2_REG_I2S_TDM_CFG_00_REG_CODEC_I2S_RX_BCK_DG_NUM_SHIFT 0

#define AUDIO_BANK2_REG_I2S_TDM_CFG_01_ADDR                           0x0C
#define AUDIO_BANK2_REG_I2S_TDM_CFG_01_REG_I2S_TDM_TX_DATA_SEL_MASK   0x1c00
#define AUDIO_BANK2_REG_I2S_TDM_CFG_01_REG_I2S_TDM_TX_DATA_SEL_SHIFT  10
#define AUDIO_BANK2_REG_I2S_TDM_CFG_01_REG_CODEC_I2S_RX_WS_WDTH_MASK  0x3e0
#define AUDIO_BANK2_REG_I2S_TDM_CFG_01_REG_CODEC_I2S_RX_WS_WDTH_SHIFT 5
#define AUDIO_BANK2_REG_I2S_TDM_CFG_01_REG_CODEC_I2S_TX_WS_WDTH_MASK  0x1f
#define AUDIO_BANK2_REG_I2S_TDM_CFG_01_REG_CODEC_I2S_TX_WS_WDTH_SHIFT 0

#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_ADDR                            0x0E
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_I2S_TDM_RX_FIFO_CLR_MASK    0x8000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_I2S_TDM_RX_FIFO_CLR_SHIFT   15
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_I2S_TDM_RX_FIFO_DEPTH_MASK  0x4000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_I2S_TDM_RX_FIFO_DEPTH_SHIFT 14
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_I2S_TDM_TX_FIFO_DEPTH_MASK  0x2000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_I2S_TDM_TX_FIFO_DEPTH_SHIFT 13
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_CODEC_I2S_TX_SDO_DLY_MASK   0xc00
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_CODEC_I2S_TX_SDO_DLY_SHIFT  10
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_CODEC_I2S_RX_WS_DLY_MASK    0x300
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_CODEC_I2S_RX_WS_DLY_SHIFT   8
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_CODEC_I2S_TX_CH_SWAP_MASK   0xf0
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_CODEC_I2S_TX_CH_SWAP_SHIFT  4
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_CODEC_I2S_RX_CH_SWAP_MASK   0xf
#define AUDIO_BANK2_REG_I2S_TDM_CFG_02_REG_CODEC_I2S_RX_CH_SWAP_SHIFT  0

#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_ADDR                        0x10
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_ENA_CH01_MASK  0x8000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_ENA_CH01_SHIFT 15
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_ENA_CH23_MASK  0x4000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_ENA_CH23_SHIFT 14
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_ENA_CH45_MASK  0x2000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_ENA_CH45_SHIFT 13
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_ENA_CH67_MASK  0x1000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_ENA_CH67_SHIFT 12
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_GAIN_MASK      0xf0
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_GAIN_SHIFT     4
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_FREQ_MASK      0xf
#define AUDIO_BANK2_REG_I2S_TDM_CFG_03_REG_SINE_GEN_FREQ_SHIFT     0

#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_ADDR                              0x14
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_CHLEN2_MASK      0x8000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_CHLEN2_SHIFT     15
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_MS_MODE_MASK     0x4000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_MS_MODE_SHIFT    14
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_CHLEN_1_MASK     0x2000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_CHLEN_1_SHIFT    13
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_4WIRE_MODE_MASK  0x1000
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_4WIRE_MODE_SHIFT 12
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_FIFO_STATUS_CLR_MASK    0x800
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_FIFO_STATUS_CLR_SHIFT   11
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_ENC_WDTH_MASK    0x200
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_ENC_WDTH_SHIFT   9
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TDM_TX_CHLEN0_MASK  0x100
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TDM_TX_CHLEN0_SHIFT 8
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_WS_FMT_MASK      0x80
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_WS_FMT_SHIFT     7
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_FMT_MASK         0x40
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_FMT_SHIFT        6
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_WS_INV_MASK      0x20
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_WS_INV_SHIFT     5
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_OUT_MODE_MASK    0x10
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_OUT_MODE_SHIFT   4
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_BCK_DG_EN_MASK   0x8
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_BCK_DG_EN_SHIFT  3
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_BCK_DG_NUM_MASK  0x7
#define AUDIO_BANK2_REG_I2S_TDM_CFG_05_REG_CODEC_I2S_TX_BCK_DG_NUM_SHIFT 0

#define AUDIO_BANK2_REG_I2S_TDM_CFG_06_ADDR                            0x16
#define AUDIO_BANK2_REG_I2S_TDM_CFG_06_REG_CODEC_I2S_TX_ACT_SLOT_MASK  0xffff
#define AUDIO_BANK2_REG_I2S_TDM_CFG_06_REG_CODEC_I2S_TX_ACT_SLOT_SHIFT 0

#define AUDIO_BANK2_REG_I2S_CFG_00_ADDR                                  0x26
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_SEL_CLK_CODEC_I2S_RX_BCK_MASK     0xc000
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_SEL_CLK_CODEC_I2S_RX_BCK_SHIFT    14
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_INV_CLK_CODEC_I2S_RX_BCK_MASK     0x2000
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_INV_CLK_CODEC_I2S_RX_BCK_SHIFT    13
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_ENABLE_CLK_CODEC_I2S_RX_BCK_MASK  0x1000
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_ENABLE_CLK_CODEC_I2S_RX_BCK_SHIFT 12
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_SEL_CLK_CODEC_I2S_TX_BCK_MASK     0xc00
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_SEL_CLK_CODEC_I2S_TX_BCK_SHIFT    10
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_INV_CLK_CODEC_I2S_TX_BCK_MASK     0x200
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_INV_CLK_CODEC_I2S_TX_BCK_SHIFT    9
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_ENABLE_CLK_CODEC_I2S_TX_BCK_MASK  0x100
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_ENABLE_CLK_CODEC_I2S_TX_BCK_SHIFT 8
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_SEL_CLK_CODEC_I2S_MCK_MASK        0xc0
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_SEL_CLK_CODEC_I2S_MCK_SHIFT       6
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_INV_CLK_CODEC_I2S_MCK_MASK        0x20
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_INV_CLK_CODEC_I2S_MCK_SHIFT       5
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_ENABLE_CLK_CODEC_I2S_MCK_MASK     0x10
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_ENABLE_CLK_CODEC_I2S_MCK_SHIFT    4
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_I2S_TDM_TX_VALID_SEL_MASK         0x8
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_I2S_TDM_TX_VALID_SEL_SHIFT        3
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_I2S_PAD_SEL_MASK                  0x1
#define AUDIO_BANK2_REG_I2S_CFG_00_REG_I2S_PAD_SEL_SHIFT                 0

#define AUDIO_BANK2_REG_CKG_CTRL0_ADDR                          0x28
#define AUDIO_BANK2_REG_CKG_CTRL0_REG_AU_SYS_24M_GATE_MASK      0x2000
#define AUDIO_BANK2_REG_CKG_CTRL0_REG_AU_SYS_24M_GATE_SHIFT     13
#define AUDIO_BANK2_REG_CKG_CTRL0_REG_AU_SYS_48M_GATE_MASK      0x4
#define AUDIO_BANK2_REG_CKG_CTRL0_REG_AU_SYS_48M_GATE_SHIFT     2
#define AUDIO_BANK2_REG_CKG_CTRL0_REG_AU_SYS_48M_INV_GATE_MASK  0x2
#define AUDIO_BANK2_REG_CKG_CTRL0_REG_AU_SYS_48M_INV_GATE_SHIFT 1
#define AUDIO_BANK2_REG_CKG_CTRL0_REG_CLK_MIU1_GATE_EN_MASK     0x1
#define AUDIO_BANK2_REG_CKG_CTRL0_REG_CLK_MIU1_GATE_EN_SHIFT    0

#define AUDIO_BANK2_REG_CKG_CTRL1_ADDR                          0x30
#define AUDIO_BANK2_REG_CKG_CTRL1_REG_AU_SYS_24M_INVT_MASK      0x2000
#define AUDIO_BANK2_REG_CKG_CTRL1_REG_AU_SYS_24M_INVT_SHIFT     13
#define AUDIO_BANK2_REG_CKG_CTRL1_REG_AU_SYS_48M_INVT_MASK      0x4
#define AUDIO_BANK2_REG_CKG_CTRL1_REG_AU_SYS_48M_INVT_SHIFT     2
#define AUDIO_BANK2_REG_CKG_CTRL1_REG_AU_SYS_48M_INV_INVT_MASK  0x2
#define AUDIO_BANK2_REG_CKG_CTRL1_REG_AU_SYS_48M_INV_INVT_SHIFT 1

#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG1_ADDR                      0x60
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG1_MMCDEC1_REG_GAIN_L_MASK   0x3ff0
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG1_MMCDEC1_REG_GAIN_L_SHIFT  4
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG1_MMCDEC1_MUTE_2_ZERO_MASK  0x4
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG1_MMCDEC1_MUTE_2_ZERO_SHIFT 2
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG1_MMCDEC1_FADING_EN_MASK    0x2
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG1_MMCDEC1_FADING_EN_SHIFT   1
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG1_MMCDEC1_DPGA_EN_MASK      0x1
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG1_MMCDEC1_DPGA_EN_SHIFT     0

#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG2_ADDR                     0x62
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG2_MMCDEC1_REG_GAIN_R_MASK  0x3ff0
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG2_MMCDEC1_REG_GAIN_R_SHIFT 4
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG2_MMCDEC1_STEP_MASK        0x7
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG2_MMCDEC1_STEP_SHIFT       0

#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG3_ADDR                       0x64
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG3_MMCDEC1_REG_OFFSET_R_MASK  0x7f00
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG3_MMCDEC1_REG_OFFSET_R_SHIFT 8
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG3_MMCDEC1_REG_OFFSET_L_MASK  0x7f
#define AUDIO_BANK2_REG_MMCDEC1_DPGA_CFG3_MMCDEC1_REG_OFFSET_L_SHIFT 0

#define AUDIO_BANK2_REG_ADC1_DPGA_CFG1_ADDR                   0x70
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG1_ADC1_REG_GAIN_L_MASK   0x3ff0
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG1_ADC1_REG_GAIN_L_SHIFT  4
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG1_ADC1_MUTE_2_ZERO_MASK  0x4
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG1_ADC1_MUTE_2_ZERO_SHIFT 2
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG1_ADC1_FADING_EN_MASK    0x2
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG1_ADC1_FADING_EN_SHIFT   1
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG1_ADC1_DPGA_EN_MASK      0x1
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG1_ADC1_DPGA_EN_SHIFT     0

#define AUDIO_BANK2_REG_ADC1_DPGA_CFG2_ADDR                  0x72
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG2_ADC1_REG_GAIN_R_MASK  0x3ff0
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG2_ADC1_REG_GAIN_R_SHIFT 4
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG2_ADC1_STEP_MASK        0x7
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG2_ADC1_STEP_SHIFT       0

#define AUDIO_BANK2_REG_ADC1_DPGA_CFG3_ADDR                    0x74
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG3_ADC1_REG_OFFSET_R_MASK  0x7f00
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG3_ADC1_REG_OFFSET_R_SHIFT 8
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG3_ADC1_REG_OFFSET_L_MASK  0x7f
#define AUDIO_BANK2_REG_ADC1_DPGA_CFG3_ADC1_REG_OFFSET_L_SHIFT 0

#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_ADDR                      0x7C
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_MUTE_INT_EN_MASK          0x8000
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_MUTE_INT_EN_SHIFT         15
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_DPGA_VLD_ERR_FRIST_MASK   0x1000
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_DPGA_VLD_ERR_FRIST_SHIFT  12
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_ADC1_MUTE_DONE_R_MASK     0x200
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_ADC1_MUTE_DONE_R_SHIFT    9
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_ADC1_MUTE_DONE_L_MASK     0x100
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_ADC1_MUTE_DONE_L_SHIFT    8
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_MMCDEC1_MUTE_DONE_R_MASK  0x20
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_MMCDEC1_MUTE_DONE_R_SHIFT 5
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_MMCDEC1_MUTE_DONE_L_MASK  0x10
#define AUDIO_BANK2_REG_DPGA_MUTE_CFG_MMCDEC1_MUTE_DONE_L_SHIFT 4

#define AUDIO_BANK2_REG_DPGA_MUTE_STS_ADDR                          0x7E
#define AUDIO_BANK2_REG_DPGA_MUTE_STS_DPGA_STATUS_MASK              0xf000
#define AUDIO_BANK2_REG_DPGA_MUTE_STS_DPGA_STATUS_SHIFT             12
#define AUDIO_BANK2_REG_DPGA_MUTE_STS_ADC1_MUTE_DONE_R_STS_MASK     0x200
#define AUDIO_BANK2_REG_DPGA_MUTE_STS_ADC1_MUTE_DONE_R_STS_SHIFT    9
#define AUDIO_BANK2_REG_DPGA_MUTE_STS_ADC1_MUTE_DONE_L_STS_MASK     0x100
#define AUDIO_BANK2_REG_DPGA_MUTE_STS_ADC1_MUTE_DONE_L_STS_SHIFT    8
#define AUDIO_BANK2_REG_DPGA_MUTE_STS_MMCDEC1_MUTE_DONE_R_STS_MASK  0x20
#define AUDIO_BANK2_REG_DPGA_MUTE_STS_MMCDEC1_MUTE_DONE_R_STS_SHIFT 5
#define AUDIO_BANK2_REG_DPGA_MUTE_STS_MMCDEC1_MUTE_DONE_L_STS_MASK  0x10
#define AUDIO_BANK2_REG_DPGA_MUTE_STS_MMCDEC1_MUTE_DONE_L_STS_SHIFT 4

#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG1_ADDR                           0x80
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG1_DMIC0_REG_GAIN_L_MASK          0x3ff0
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG1_DMIC0_REG_GAIN_L_SHIFT         4
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG1_REG_DMIC_DPGA_STATUS_CLR_MASK  0x8
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG1_REG_DMIC_DPGA_STATUS_CLR_SHIFT 3
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG1_DMIC0_MUTE_2_ZERO_MASK         0x4
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG1_DMIC0_MUTE_2_ZERO_SHIFT        2
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG1_DMIC0_FADING_EN_MASK           0x2
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG1_DMIC0_FADING_EN_SHIFT          1
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG1_DMIC0_DPGA_EN_MASK             0x1
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG1_DMIC0_DPGA_EN_SHIFT            0

#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG2_ADDR                   0x82
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG2_DMIC0_REG_GAIN_R_MASK  0x3ff0
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG2_DMIC0_REG_GAIN_R_SHIFT 4
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG2_DMIC0_STEP_MASK        0x7
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG2_DMIC0_STEP_SHIFT       0

#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG3_ADDR                     0x84
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG3_DMIC0_REG_OFFSET_R_MASK  0x7f00
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG3_DMIC0_REG_OFFSET_R_SHIFT 8
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG3_DMIC0_REG_OFFSET_L_MASK  0x7f
#define AUDIO_BANK2_REG_DMIC_CH01_DPGA_CFG3_DMIC0_REG_OFFSET_L_SHIFT 0

#define AUDIO_BANK2_REG_DMIC0123_MUTE_DONE_LR_ADDR                       0xDC
#define AUDIO_BANK2_REG_DMIC0123_MUTE_DONE_LR_DMIC0_MUTE_DONE_R_MASK     0x200
#define AUDIO_BANK2_REG_DMIC0123_MUTE_DONE_LR_DMIC0_MUTE_DONE_R_SHIFT    9
#define AUDIO_BANK2_REG_DMIC0123_MUTE_DONE_LR_DMIC0_MUTE_DONE_L_MASK     0x100
#define AUDIO_BANK2_REG_DMIC0123_MUTE_DONE_LR_DMIC0_MUTE_DONE_L_SHIFT    8
#define AUDIO_BANK2_REG_DMIC0123_MUTE_DONE_LR_REG_DMIC_DPGA_STATUS_MASK  0x1f
#define AUDIO_BANK2_REG_DMIC0123_MUTE_DONE_LR_REG_DMIC_DPGA_STATUS_SHIFT 0

#define AUDIO_BANK2_REG_MMC12_MUTE_DONE_RL_ADDR                         0xE2
#define AUDIO_BANK2_REG_MMC12_MUTE_DONE_RL_MMC1_DPGA1_MUTE_DONE_R_MASK  0x2
#define AUDIO_BANK2_REG_MMC12_MUTE_DONE_RL_MMC1_DPGA1_MUTE_DONE_R_SHIFT 1
#define AUDIO_BANK2_REG_MMC12_MUTE_DONE_RL_MMC1_DPGA1_MUTE_DONE_L_MASK  0x1
#define AUDIO_BANK2_REG_MMC12_MUTE_DONE_RL_MMC1_DPGA1_MUTE_DONE_L_SHIFT 0

#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG0_ADDR                     0xE4
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG0_MMC1_1_REG_GAIN_L_MASK   0x3ff0
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG0_MMC1_1_REG_GAIN_L_SHIFT  4
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG0_MMC1_1_MUTE_2_ZERO_MASK  0x4
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG0_MMC1_1_MUTE_2_ZERO_SHIFT 2
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG0_MMC1_1_FADING_EN_MASK    0x2
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG0_MMC1_1_FADING_EN_SHIFT   1
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG0_MMC1_1_DPGA_EN_MASK      0x1
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG0_MMC1_1_DPGA_EN_SHIFT     0

#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG1_ADDR                    0xE6
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG1_MMC1_1_REG_GAIN_R_MASK  0x3ff0
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG1_MMC1_1_REG_GAIN_R_SHIFT 4
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG1_MMC1_1_STEP_MASK        0x7
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG1_MMC1_1_STEP_SHIFT       0

#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG2_ADDR                      0xE8
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG2_MMC1_1_REG_OFFSET_R_MASK  0x7f00
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG2_MMC1_1_REG_OFFSET_R_SHIFT 8
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG2_MMC1_1_REG_OFFSET_L_MASK  0x7f
#define AUDIO_BANK2_REG_MMC1_DPGA1_CFG2_MMC1_1_REG_OFFSET_L_SHIFT 0

#endif
