/*
 * audio_ausdm0_sw_reg_define.h - Sigmastar
 *
 * Copyright (c) [2019~2022] SigmaStar Technology.
 *
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details.
 *
 */

#ifndef __JM_AUDIO_AUSDM_SW_REG_DEFINE_H__
#define __JM_AUDIO_AUSDM_SW_REG_DEFINE_H__

#define AUDIO_AUSDM_REG_AUSDM_00_ADDR                         0x00
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_MSP_DAC_MASK          0x8000
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_MSP_DAC_SHIFT         15
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_VREF_DISCH_DAC_MASK   0x4000
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_VREF_DISCH_DAC_SHIFT  14
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_VREF_SFTDCH_DAC_MASK  0x3000
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_VREF_SFTDCH_DAC_SHIFT 12
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_MSP_MASK              0x800
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_MSP_SHIFT             11
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_ITEST_DAC_MASK        0x400
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_ITEST_DAC_SHIFT       10
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_EXT_CK_MASK           0x200
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_EXT_CK_SHIFT          9
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_DAC_DISCH_MASK        0x100
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_DAC_DISCH_SHIFT       8
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_CK_DAC_MASK           0xf0
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_CK_DAC_SHIFT          4
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_BYP_INMUX_R_MASK      0x2
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_BYP_INMUX_R_SHIFT     1
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_BYP_INMUX_L_MASK      0x1
#define AUDIO_AUSDM_REG_AUSDM_00_REG_EN_BYP_INMUX_L_SHIFT     0

#define AUDIO_AUSDM_REG_AUSDM_01_ADDR                      0x02
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_VREF_SFTDCH_MASK   0x1800
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_VREF_SFTDCH_SHIFT  11
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_VREF_DISCH_MASK    0x400
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_VREF_DISCH_SHIFT   10
#define AUDIO_AUSDM_REG_AUSDM_01_REG_IGEN_IBIAS_SEL_MASK   0x300
#define AUDIO_AUSDM_REG_AUSDM_01_REG_IGEN_IBIAS_SEL_SHIFT  8
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_SHRT_R_MASK        0x80
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_SHRT_R_SHIFT       7
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_SHRT_L_MASK        0x40
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_SHRT_L_SHIFT       6
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_MUTE_INMUX_R_MASK  0x2
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_MUTE_INMUX_R_SHIFT 1
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_MUTE_INMUX_L_MASK  0x1
#define AUDIO_AUSDM_REG_AUSDM_01_REG_EN_MUTE_INMUX_L_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_02_ADDR                   0x04
#define AUDIO_AUSDM_REG_AUSDM_02_REG_ADC_LDO_TEST_MASK  0xf000
#define AUDIO_AUSDM_REG_AUSDM_02_REG_ADC_LDO_TEST_SHIFT 12
#define AUDIO_AUSDM_REG_AUSDM_02_REG_EN_SW_TEST_MASK    0x3ff
#define AUDIO_AUSDM_REG_AUSDM_02_REG_EN_SW_TEST_SHIFT   0

#define AUDIO_AUSDM_REG_AUSDM_03_ADDR                  0x06
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_SS_OP_MASK     0x2000
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_SS_OP_SHIFT    13
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_VREF_MASK      0x1000
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_VREF_SHIFT     12
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_IGEN_MASK      0x800
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_IGEN_SHIFT     11
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_REF_DAC_MASK   0x400
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_REF_DAC_SHIFT  10
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_R0_DAC_MASK    0x200
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_R0_DAC_SHIFT   9
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_INT_R_MASK     0x100
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_INT_R_SHIFT    8
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_INT_L_MASK     0x80
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_INT_L_SHIFT    7
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_LDO_ADC_MASK   0x20
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_LDO_ADC_SHIFT  5
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_L0_DAC_MASK    0x10
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_L0_DAC_SHIFT   4
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_INMUX_R_MASK   0x8
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_INMUX_R_SHIFT  3
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_INMUX_L_MASK   0x4
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_INMUX_L_SHIFT  2
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_BIAS_DAC_MASK  0x2
#define AUDIO_AUSDM_REG_AUSDM_03_REG_PD_BIAS_DAC_SHIFT 1

#define AUDIO_AUSDM_REG_AUSDM_04_ADDR                0x08
#define AUDIO_AUSDM_REG_AUSDM_04_REG_RESET_DAC_MASK  0xf0
#define AUDIO_AUSDM_REG_AUSDM_04_REG_RESET_DAC_SHIFT 4

#define AUDIO_AUSDM_REG_AUSDM_05_ADDR                      0x0A
#define AUDIO_AUSDM_REG_AUSDM_05_REG_SEL_CK_EDGE_DAC_MASK  0x2000
#define AUDIO_AUSDM_REG_AUSDM_05_REG_SEL_CK_EDGE_DAC_SHIFT 13
#define AUDIO_AUSDM_REG_AUSDM_05_REG_SEL_BIAS_DAC_MASK     0x300
#define AUDIO_AUSDM_REG_AUSDM_05_REG_SEL_BIAS_DAC_SHIFT    8
#define AUDIO_AUSDM_REG_AUSDM_05_REG_CH_INMUX_R_MASK       0x70
#define AUDIO_AUSDM_REG_AUSDM_05_REG_CH_INMUX_R_SHIFT      4
#define AUDIO_AUSDM_REG_AUSDM_05_REG_CH_INMUX_L_MASK       0x7
#define AUDIO_AUSDM_REG_AUSDM_05_REG_CH_INMUX_L_SHIFT      0

#define AUDIO_AUSDM_REG_AUSDM_06_ADDR                    0x0C
#define AUDIO_AUSDM_REG_AUSDM_06_REG_SEL_CK_RTCPLL_MASK  0x100
#define AUDIO_AUSDM_REG_AUSDM_06_REG_SEL_CK_RTCPLL_SHIFT 8
#define AUDIO_AUSDM_REG_AUSDM_06_REG_GAIN_INMUX_R_MASK   0xf0
#define AUDIO_AUSDM_REG_AUSDM_06_REG_GAIN_INMUX_R_SHIFT  4
#define AUDIO_AUSDM_REG_AUSDM_06_REG_GAIN_INMUX_L_MASK   0xf
#define AUDIO_AUSDM_REG_AUSDM_06_REG_GAIN_INMUX_L_SHIFT  0

#define AUDIO_AUSDM_REG_AUSDM_07_ADDR                  0x0E
#define AUDIO_AUSDM_REG_AUSDM_07_REG_IBIAS_INMUX_MASK  0x300
#define AUDIO_AUSDM_REG_AUSDM_07_REG_IBIAS_INMUX_SHIFT 8

#define AUDIO_AUSDM_REG_AUSDM_08_ADDR                 0x10
#define AUDIO_AUSDM_REG_AUSDM_08_REG_SEL_DAC_SW_MASK  0xc00
#define AUDIO_AUSDM_REG_AUSDM_08_REG_SEL_DAC_SW_SHIFT 10
#define AUDIO_AUSDM_REG_AUSDM_08_REG_INT_GAIN_R_MASK  0x30
#define AUDIO_AUSDM_REG_AUSDM_08_REG_INT_GAIN_R_SHIFT 4
#define AUDIO_AUSDM_REG_AUSDM_08_REG_INT_GAIN_L_MASK  0x3
#define AUDIO_AUSDM_REG_AUSDM_08_REG_INT_GAIN_L_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_09_ADDR                  0x12
#define AUDIO_AUSDM_REG_AUSDM_09_REG_DAC_SW_TEST_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_09_REG_DAC_SW_TEST_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_10_ADDR                0x14
#define AUDIO_AUSDM_REG_AUSDM_10_REG_DLF_DEM_R_MASK  0xf000
#define AUDIO_AUSDM_REG_AUSDM_10_REG_DLF_DEM_R_SHIFT 12
#define AUDIO_AUSDM_REG_AUSDM_10_REG_DLF_DEM_L_MASK  0xf00
#define AUDIO_AUSDM_REG_AUSDM_10_REG_DLF_DEM_L_SHIFT 8
#define AUDIO_AUSDM_REG_AUSDM_10_REG_DIT_ADC_R_MASK  0xf0
#define AUDIO_AUSDM_REG_AUSDM_10_REG_DIT_ADC_R_SHIFT 4
#define AUDIO_AUSDM_REG_AUSDM_10_REG_DIT_ADC_L_MASK  0xf
#define AUDIO_AUSDM_REG_AUSDM_10_REG_DIT_ADC_L_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_11_ADDR               0x16
#define AUDIO_AUSDM_REG_AUSDM_11_REG_DLF_D1_R_MASK  0x1f00
#define AUDIO_AUSDM_REG_AUSDM_11_REG_DLF_D1_R_SHIFT 8
#define AUDIO_AUSDM_REG_AUSDM_11_REG_DLF_D1_L_MASK  0x1f
#define AUDIO_AUSDM_REG_AUSDM_11_REG_DLF_D1_L_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_12_ADDR               0x18
#define AUDIO_AUSDM_REG_AUSDM_12_REG_DLF_D2_R_MASK  0x1f00
#define AUDIO_AUSDM_REG_AUSDM_12_REG_DLF_D2_R_SHIFT 8
#define AUDIO_AUSDM_REG_AUSDM_12_REG_DLF_D2_L_MASK  0x1f
#define AUDIO_AUSDM_REG_AUSDM_12_REG_DLF_D2_L_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_13_ADDR               0x1A
#define AUDIO_AUSDM_REG_AUSDM_13_REG_DLF_FZ_R_MASK  0x1f00
#define AUDIO_AUSDM_REG_AUSDM_13_REG_DLF_FZ_R_SHIFT 8
#define AUDIO_AUSDM_REG_AUSDM_13_REG_DLF_FZ_L_MASK  0x1f
#define AUDIO_AUSDM_REG_AUSDM_13_REG_DLF_FZ_L_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_14_ADDR                      0x1C
#define AUDIO_AUSDM_REG_AUSDM_14_REG_AU_ADC_TEST_LOW_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_14_REG_AU_ADC_TEST_LOW_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_15_ADDR                       0x1E
#define AUDIO_AUSDM_REG_AUSDM_15_REG_AU_ADC_TEST_HIGH_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_15_REG_AU_ADC_TEST_HIGH_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_16_ADDR                  0x20
#define AUDIO_AUSDM_REG_AUSDM_16_REG_AUSDM_CTRL0_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_16_REG_AUSDM_CTRL0_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_17_ADDR                  0x22
#define AUDIO_AUSDM_REG_AUSDM_17_REG_AUSDM_CTRL1_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_17_REG_AUSDM_CTRL1_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_18_ADDR                  0x24
#define AUDIO_AUSDM_REG_AUSDM_18_REG_AUSDM_CTRL2_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_18_REG_AUSDM_CTRL2_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_19_ADDR                  0x26
#define AUDIO_AUSDM_REG_AUSDM_19_REG_AUSDM_CTRL3_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_19_REG_AUSDM_CTRL3_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_20_ADDR                  0x28
#define AUDIO_AUSDM_REG_AUSDM_20_REG_AUSDM_CTRL4_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_20_REG_AUSDM_CTRL4_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_21_ADDR                  0x2A
#define AUDIO_AUSDM_REG_AUSDM_21_REG_AUSDM_CTRL5_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_21_REG_AUSDM_CTRL5_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_22_ADDR                  0x2C
#define AUDIO_AUSDM_REG_AUSDM_22_REG_AUSDM_CTRL6_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_22_REG_AUSDM_CTRL6_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_23_ADDR              0x2E
#define AUDIO_AUSDM_REG_AUSDM_23_REG_AU_TEST_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_23_REG_AU_TEST_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_27_ADDR                    0x40
#define AUDIO_AUSDM_REG_AUSDM_27_REG_READY_R_MASK        0x8000
#define AUDIO_AUSDM_REG_AUSDM_27_REG_READY_R_SHIFT       15
#define AUDIO_AUSDM_REG_AUSDM_27_REG_READY_L_MASK        0x4000
#define AUDIO_AUSDM_REG_AUSDM_27_REG_READY_L_SHIFT       14
#define AUDIO_AUSDM_REG_AUSDM_27_REG_AUSDM_STATUS0_MASK  0x3fff
#define AUDIO_AUSDM_REG_AUSDM_27_REG_AUSDM_STATUS0_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_28_ADDR                    0x42
#define AUDIO_AUSDM_REG_AUSDM_28_REG_AUSDM_STATUS1_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_28_REG_AUSDM_STATUS1_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_29_ADDR                    0x44
#define AUDIO_AUSDM_REG_AUSDM_29_REG_AUSDM_STATUS2_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_29_REG_AUSDM_STATUS2_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_30_ADDR                    0x46
#define AUDIO_AUSDM_REG_AUSDM_30_REG_AUSDM_STATUS3_MASK  0xffff
#define AUDIO_AUSDM_REG_AUSDM_30_REG_AUSDM_STATUS3_SHIFT 0

#define AUDIO_AUSDM_REG_AUSDM_31_ADDR                     0x60
#define AUDIO_AUSDM_REG_AUSDM_31_REG_SAR_TIMER_R_MASK     0x3000
#define AUDIO_AUSDM_REG_AUSDM_31_REG_SAR_TIMER_R_SHIFT    12
#define AUDIO_AUSDM_REG_AUSDM_31_REG_SAR_TIMER_L_MASK     0x300
#define AUDIO_AUSDM_REG_AUSDM_31_REG_SAR_TIMER_L_SHIFT    8
#define AUDIO_AUSDM_REG_AUSDM_31_REG_PD_SAR_R_MASK        0x8
#define AUDIO_AUSDM_REG_AUSDM_31_REG_PD_SAR_R_SHIFT       3
#define AUDIO_AUSDM_REG_AUSDM_31_REG_PD_SAR_L_MASK        0x4
#define AUDIO_AUSDM_REG_AUSDM_31_REG_PD_SAR_L_SHIFT       2
#define AUDIO_AUSDM_REG_AUSDM_31_REG_EN_SAR_LOGIC_R_MASK  0x2
#define AUDIO_AUSDM_REG_AUSDM_31_REG_EN_SAR_LOGIC_R_SHIFT 1
#define AUDIO_AUSDM_REG_AUSDM_31_REG_EN_SAR_LOGIC_L_MASK  0x1
#define AUDIO_AUSDM_REG_AUSDM_31_REG_EN_SAR_LOGIC_L_SHIFT 0

#endif
