/*
 * gpi-irqs.h- Sigmastar
 *
 * Copyright (c) [2019~2020] SigmaStar Technology.
 *
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details.
 *
 */
/*------------------------------------------------------------------------------

------------------------------------------------------------------------------*/

#define GPI_FIQ_START                      0
#define INT_GPI_FIQ_PAD_PWM_OUT0           (GPI_FIQ_START + 0)
#define INT_GPI_FIQ_PAD_PWM_OUT1           (GPI_FIQ_START + 1)
#define INT_GPI_FIQ_PAD_PWM_OUT2           (GPI_FIQ_START + 2)
#define INT_GPI_FIQ_PAD_PWM_OUT3           (GPI_FIQ_START + 3)
#define INT_GPI_FIQ_PAD_PWM_OUT4           (GPI_FIQ_START + 4)
#define INT_GPI_FIQ_PAD_PWM_OUT5           (GPI_FIQ_START + 5)
#define INT_GPI_FIQ_PAD_PWM_OUT6           (GPI_FIQ_START + 6)
#define INT_GPI_FIQ_PAD_PWM_OUT7           (GPI_FIQ_START + 7)
#define INT_GPI_FIQ_PAD_SD0_GPIO0          (GPI_FIQ_START + 8)
#define INT_GPI_FIQ_PAD_SD0_VCTRL          (GPI_FIQ_START + 9)
#define INT_GPI_FIQ_PAD_SD0_CDZ            (GPI_FIQ_START + 10)
#define INT_GPI_FIQ_PAD_SD0_D1             (GPI_FIQ_START + 11)
#define INT_GPI_FIQ_PAD_SD0_D0             (GPI_FIQ_START + 12)
#define INT_GPI_FIQ_PAD_SD0_CLK            (GPI_FIQ_START + 13)
#define INT_GPI_FIQ_PAD_SD0_CMD            (GPI_FIQ_START + 14)
#define INT_GPI_FIQ_PAD_SD0_D3             (GPI_FIQ_START + 15)
#define INT_GPI_FIQ_PAD_SD0_D2             (GPI_FIQ_START + 16)
#define INT_GPI_FIQ_PAD_I2C0_SCL           (GPI_FIQ_START + 17)
#define INT_GPI_FIQ_PAD_I2C0_SDA           (GPI_FIQ_START + 18)
#define INT_GPI_FIQ_PAD_SR_RST0            (GPI_FIQ_START + 19)
#define INT_GPI_FIQ_PAD_SR_MCLK0           (GPI_FIQ_START + 20)
#define INT_GPI_FIQ_PAD_I2C1_SCL           (GPI_FIQ_START + 21)
#define INT_GPI_FIQ_PAD_I2C1_SDA           (GPI_FIQ_START + 22)
#define INT_GPI_FIQ_PAD_SR_RST1            (GPI_FIQ_START + 23)
#define INT_GPI_FIQ_PAD_SR_MCLK1           (GPI_FIQ_START + 24)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH0       (GPI_FIQ_START + 25)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH0       (GPI_FIQ_START + 26)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH1       (GPI_FIQ_START + 27)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH1       (GPI_FIQ_START + 28)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH2       (GPI_FIQ_START + 29)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH2       (GPI_FIQ_START + 30)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH3       (GPI_FIQ_START + 31)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH3       (GPI_FIQ_START + 32)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH4       (GPI_FIQ_START + 33)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH4       (GPI_FIQ_START + 34)
#define INT_GPI_FIQ_PAD_OUTP_RX0_CH5       (GPI_FIQ_START + 35)
#define INT_GPI_FIQ_PAD_OUTN_RX0_CH5       (GPI_FIQ_START + 36)
#define INT_GPI_FIQ_PAD_OUTP_RX1_CH0       (GPI_FIQ_START + 37)
#define INT_GPI_FIQ_PAD_OUTN_RX1_CH0       (GPI_FIQ_START + 38)
#define INT_GPI_FIQ_PAD_OUTP_RX1_CH1       (GPI_FIQ_START + 39)
#define INT_GPI_FIQ_PAD_OUTN_RX1_CH1       (GPI_FIQ_START + 40)
#define INT_GPI_FIQ_PAD_OUTP_RX1_CH2       (GPI_FIQ_START + 41)
#define INT_GPI_FIQ_PAD_OUTN_RX1_CH2       (GPI_FIQ_START + 42)
#define INT_GPI_FIQ_PAD_OUTP_RX1_CH3       (GPI_FIQ_START + 43)
#define INT_GPI_FIQ_PAD_OUTN_RX1_CH3       (GPI_FIQ_START + 44)
#define INT_GPI_FIQ_PAD_OUTP_RX1_CH4       (GPI_FIQ_START + 45)
#define INT_GPI_FIQ_PAD_OUTN_RX1_CH4       (GPI_FIQ_START + 46)
#define INT_GPI_FIQ_PAD_OUTP_RX2_CH0       (GPI_FIQ_START + 47)
#define INT_GPI_FIQ_PAD_OUTN_RX2_CH0       (GPI_FIQ_START + 48)
#define INT_GPI_FIQ_PAD_OUTP_RX2_CH1       (GPI_FIQ_START + 49)
#define INT_GPI_FIQ_PAD_OUTN_RX2_CH1       (GPI_FIQ_START + 50)
#define INT_GPI_FIQ_PAD_OUTP_RX2_CH2       (GPI_FIQ_START + 51)
#define INT_GPI_FIQ_PAD_OUTN_RX2_CH2       (GPI_FIQ_START + 52)
#define INT_GPI_FIQ_PAD_I2C2_SCL           (GPI_FIQ_START + 53)
#define INT_GPI_FIQ_PAD_I2C2_SDA           (GPI_FIQ_START + 54)
#define INT_GPI_FIQ_PAD_SR_RST2            (GPI_FIQ_START + 55)
#define INT_GPI_FIQ_PAD_SR_MCLK2           (GPI_FIQ_START + 56)
#define INT_GPI_FIQ_PAD_I2C3_SCL           (GPI_FIQ_START + 57)
#define INT_GPI_FIQ_PAD_I2C3_SDA           (GPI_FIQ_START + 58)
#define INT_GPI_FIQ_PAD_SR_RST3            (GPI_FIQ_START + 59)
#define INT_GPI_FIQ_PAD_SR_MCLK3           (GPI_FIQ_START + 60)
#define INT_GPI_FIQ_PAD_ISP0_XVS           (GPI_FIQ_START + 61)
#define INT_GPI_FIQ_PAD_ISP0_XHS           (GPI_FIQ_START + 62)
#define INT_GPI_FIQ_PAD_ISP0_XTRIG         (GPI_FIQ_START + 63)
#define INT_GPI_FIQ_PAD_PM_SR1_D0          (GPI_FIQ_START + 64)
#define INT_GPI_FIQ_PAD_PM_SR1_D4          (GPI_FIQ_START + 65)
#define INT_GPI_FIQ_PAD_PM_SR1_PCLK        (GPI_FIQ_START + 66)
#define INT_GPI_FIQ_PAD_PM_SR1_RST         (GPI_FIQ_START + 67)
#define INT_GPI_FIQ_PAD_PM_SR1_INT         (GPI_FIQ_START + 68)
#define INT_GPI_FIQ_PAD_PM_MI2C1_SCL       (GPI_FIQ_START + 69)
#define INT_GPI_FIQ_PAD_PM_MI2C1_SDA       (GPI_FIQ_START + 70)
#define INT_GPI_FIQ_PAD_PM_SR1_D1          (GPI_FIQ_START + 71)
#define INT_GPI_FIQ_PAD_PM_SR1_D2          (GPI_FIQ_START + 72)
#define INT_GPI_FIQ_PAD_PM_SR1_D3          (GPI_FIQ_START + 73)
#define INT_GPI_FIQ_PAD_PM_SR1_D5          (GPI_FIQ_START + 74)
#define INT_GPI_FIQ_PAD_PM_SR1_D6          (GPI_FIQ_START + 75)
#define INT_GPI_FIQ_PAD_PM_SR1_D7          (GPI_FIQ_START + 76)
#define INT_GPI_FIQ_PAD_PM_SR1_VS          (GPI_FIQ_START + 77)
#define INT_GPI_FIQ_PAD_PM_SR1_HS          (GPI_FIQ_START + 78)
#define INT_GPI_FIQ_PAD_PM_DMIC0_CLK       (GPI_FIQ_START + 79)
#define INT_GPI_FIQ_PAD_PM_DMIC0_D0        (GPI_FIQ_START + 80)
#define INT_GPI_FIQ_PAD_PM_SPI_CK          (GPI_FIQ_START + 81)
#define INT_GPI_FIQ_PAD_PM_SPI_DI          (GPI_FIQ_START + 82)
#define INT_GPI_FIQ_PAD_PM_SPI_HLD         (GPI_FIQ_START + 83)
#define INT_GPI_FIQ_PAD_PM_SPI_DO          (GPI_FIQ_START + 84)
#define INT_GPI_FIQ_PAD_PM_SPI_WPZ         (GPI_FIQ_START + 85)
#define INT_GPI_FIQ_PAD_PM_SPI_CZ          (GPI_FIQ_START + 86)
#define INT_GPI_FIQ_PAD_PM_RADAR_SAR_GPIO0 (GPI_FIQ_START + 87)
#define INT_GPI_FIQ_PAD_PM_RADAR_SAR_GPIO1 (GPI_FIQ_START + 88)
#define INT_GPI_FIQ_PAD_PM_RADAR_SAR_GPIO2 (GPI_FIQ_START + 89)
#define INT_GPI_FIQ_PAD_PM_RADAR_SAR_GPIO3 (GPI_FIQ_START + 90)
#define INT_GPI_FIQ_PAD_PM_UART_RX         (GPI_FIQ_START + 91)
#define INT_GPI_FIQ_PAD_PM_UART_TX         (GPI_FIQ_START + 92)
#define INT_GPI_FIQ_PAD_PM_INTOUT          (GPI_FIQ_START + 93)
#define INT_GPI_FIQ_PAD_PM_GPIO0           (GPI_FIQ_START + 94)
#define INT_GPI_FIQ_PAD_PM_GPIO1           (GPI_FIQ_START + 95)
#define INT_GPI_FIQ_PAD_PM_GPIO2           (GPI_FIQ_START + 96)
#define INT_GPI_FIQ_PAD_PM_GPIO3           (GPI_FIQ_START + 97)
#define INT_GPI_FIQ_PAD_PM_GPIO4           (GPI_FIQ_START + 98)
#define INT_GPI_FIQ_PAD_PM_GPIO5           (GPI_FIQ_START + 99)
#define INT_GPI_FIQ_PAD_PM_FUART_RX        (GPI_FIQ_START + 100)
#define INT_GPI_FIQ_PAD_PM_FUART_TX        (GPI_FIQ_START + 101)
#define INT_GPI_FIQ_PAD_PM_IRIN            (GPI_FIQ_START + 102)
#define INT_GPI_FIQ_PAD_PM_MSPI0_DO        (GPI_FIQ_START + 103)
#define INT_GPI_FIQ_PAD_PM_MSPI0_DI        (GPI_FIQ_START + 104)
#define INT_GPI_FIQ_PAD_PM_MSPI0_CK        (GPI_FIQ_START + 105)
#define INT_GPI_FIQ_PAD_PM_MSPI0_CZ        (GPI_FIQ_START + 106)
#define INT_GPI_FIQ_PAD_PM_USB3_INT        (GPI_FIQ_START + 107)
#define INT_GPI_FIQ_PAD_PM_USB3_ID         (GPI_FIQ_START + 108)
#define INT_GPI_FIQ_PAD_RGMII0_MCLK        (GPI_FIQ_START + 109)
#define INT_GPI_FIQ_PAD_RGMII0_RSTN        (GPI_FIQ_START + 110)
#define INT_GPI_FIQ_PAD_RGMII0_RXCLK       (GPI_FIQ_START + 111)
#define INT_GPI_FIQ_PAD_RGMII0_RXCTL       (GPI_FIQ_START + 112)
#define INT_GPI_FIQ_PAD_RGMII0_RXD0        (GPI_FIQ_START + 113)
#define INT_GPI_FIQ_PAD_RGMII0_RXD1        (GPI_FIQ_START + 114)
#define INT_GPI_FIQ_PAD_RGMII0_RXD2        (GPI_FIQ_START + 115)
#define INT_GPI_FIQ_PAD_RGMII0_RXD3        (GPI_FIQ_START + 116)
#define INT_GPI_FIQ_PAD_RGMII0_TXCLK       (GPI_FIQ_START + 117)
#define INT_GPI_FIQ_PAD_RGMII0_TXCTL       (GPI_FIQ_START + 118)
#define INT_GPI_FIQ_PAD_RGMII0_TXD0        (GPI_FIQ_START + 119)
#define INT_GPI_FIQ_PAD_RGMII0_TXD1        (GPI_FIQ_START + 120)
#define INT_GPI_FIQ_PAD_RGMII0_TXD2        (GPI_FIQ_START + 121)
#define INT_GPI_FIQ_PAD_RGMII0_TXD3        (GPI_FIQ_START + 122)
#define INT_GPI_FIQ_PAD_RGMII0_MDIO        (GPI_FIQ_START + 123)
#define INT_GPI_FIQ_PAD_RGMII0_MDC         (GPI_FIQ_START + 124)
#define INT_GPI_FIQ_PAD_SD1_GPIO0          (GPI_FIQ_START + 125)
#define INT_GPI_FIQ_PAD_SD1_GPIO1          (GPI_FIQ_START + 126)
#define INT_GPI_FIQ_PAD_SD1_CDZ            (GPI_FIQ_START + 127)
#define INT_GPI_FIQ_PAD_SD1_D1             (GPI_FIQ_START + 128)
#define INT_GPI_FIQ_PAD_SD1_D0             (GPI_FIQ_START + 129)
#define INT_GPI_FIQ_PAD_SD1_CLK            (GPI_FIQ_START + 130)
#define INT_GPI_FIQ_PAD_SD1_CMD            (GPI_FIQ_START + 131)
#define INT_GPI_FIQ_PAD_SD1_D3             (GPI_FIQ_START + 132)
#define INT_GPI_FIQ_PAD_SD1_D2             (GPI_FIQ_START + 133)
#define INT_GPI_FIQ_PAD_OUTP_TX0_CH0       (GPI_FIQ_START + 134)
#define INT_GPI_FIQ_PAD_OUTN_TX0_CH0       (GPI_FIQ_START + 135)
#define INT_GPI_FIQ_PAD_OUTP_TX0_CH1       (GPI_FIQ_START + 136)
#define INT_GPI_FIQ_PAD_OUTN_TX0_CH1       (GPI_FIQ_START + 137)
#define INT_GPI_FIQ_PAD_OUTP_TX0_CH2       (GPI_FIQ_START + 138)
#define INT_GPI_FIQ_PAD_OUTN_TX0_CH2       (GPI_FIQ_START + 139)
#define INT_GPI_FIQ_PAD_OUTP_TX0_CH3       (GPI_FIQ_START + 140)
#define INT_GPI_FIQ_PAD_OUTN_TX0_CH3       (GPI_FIQ_START + 141)
#define INT_GPI_FIQ_PAD_OUTP_TX0_CH4       (GPI_FIQ_START + 142)
#define INT_GPI_FIQ_PAD_OUTN_TX0_CH4       (GPI_FIQ_START + 143)
#define INT_GPI_FIQ_PAD_EMMC_RSTN          (GPI_FIQ_START + 144)
#define INT_GPI_FIQ_PAD_EMMC_CLK           (GPI_FIQ_START + 145)
#define INT_GPI_FIQ_PAD_EMMC_CMD           (GPI_FIQ_START + 146)
#define INT_GPI_FIQ_PAD_EMMC_DS            (GPI_FIQ_START + 147)
#define INT_GPI_FIQ_PAD_EMMC_D3            (GPI_FIQ_START + 148)
#define INT_GPI_FIQ_PAD_EMMC_D4            (GPI_FIQ_START + 149)
#define INT_GPI_FIQ_PAD_EMMC_D0            (GPI_FIQ_START + 150)
#define INT_GPI_FIQ_PAD_EMMC_D5            (GPI_FIQ_START + 151)
#define INT_GPI_FIQ_PAD_EMMC_D1            (GPI_FIQ_START + 152)
#define INT_GPI_FIQ_PAD_EMMC_D6            (GPI_FIQ_START + 153)
#define INT_GPI_FIQ_PAD_EMMC_D2            (GPI_FIQ_START + 154)
#define INT_GPI_FIQ_PAD_EMMC_D7            (GPI_FIQ_START + 155)
#define INT_GPI_FIQ_PAD_ETH_LED0           (GPI_FIQ_START + 156)
#define INT_GPI_FIQ_PAD_ETH_LED1           (GPI_FIQ_START + 157)
#define INT_GPI_FIQ_PAD_I2C4_SCL           (GPI_FIQ_START + 158)
#define INT_GPI_FIQ_PAD_I2C4_SDA           (GPI_FIQ_START + 159)
#define INT_GPI_FIQ_PAD_SPI_CK             (GPI_FIQ_START + 160)
#define INT_GPI_FIQ_PAD_SPI_DI             (GPI_FIQ_START + 161)
#define INT_GPI_FIQ_PAD_SPI_HLD            (GPI_FIQ_START + 162)
#define INT_GPI_FIQ_PAD_SPI_DO             (GPI_FIQ_START + 163)
#define INT_GPI_FIQ_PAD_SPI_WPZ            (GPI_FIQ_START + 164)
#define INT_GPI_FIQ_PAD_SPI_CZ             (GPI_FIQ_START + 165)
#define INT_GPI_FIQ_PAD_UART_RX            (GPI_FIQ_START + 166)
#define INT_GPI_FIQ_PAD_UART_TX            (GPI_FIQ_START + 167)
#define GPI_FIQ_END                        (GPI_FIQ_START + 168)

#define GPI_GPIC_START    (GPI_FIQ_START + 168)
#define INT_GPI_FIQ_GPIC0 (GPI_FIQ_START + 169)
#define INT_GPI_FIQ_GPIC1 (GPI_FIQ_START + 170)
#define GPI_GPIC_END      (GPI_FIQ_START + 171)

#define GPI_FIQ_NUM  (GPI_FIQ_END - GPI_FIQ_START)
#define GPI_GPIC_NUM (GPI_GPIC_END - GPI_GPIC_START)

#define INT_GPI_FIQ_INVAILD (-2)

#define GPI_IRQ_START       0
#define INT_GPI_IRQ_DUMMY00 (GPI_IRQ_START + 0)
#define INT_GPI_IRQ_DUMMY01 (GPI_IRQ_START + 1)
#define INT_GPI_IRQ_DUMMY02 (GPI_IRQ_START + 2)
#define INT_GPI_IRQ_DUMMY03 (GPI_IRQ_START + 3)
#define INT_GPI_IRQ_DUMMY04 (GPI_IRQ_START + 4)
#define INT_GPI_IRQ_DUMMY05 (GPI_IRQ_START + 5)
#define INT_GPI_IRQ_DUMMY06 (GPI_IRQ_START + 6)
#define INT_GPI_IRQ_DUMMY07 (GPI_IRQ_START + 7)
#define GPI_IRQ_END         (GPI_IRQ_START + 8)
#define GPI_IRQ_NUM         (GPI_IRQ_END - GPI_IRQ_START)
